import type { FighterDefinition } from '../types/combat';
import { CROUCHING_HURTBOXES, STANDING_HURTBOXES, STANDARD_ANIMATIONS } from './shared';

/**
 * Astro Riso troca dano bruto por velocidade, recuperação curta e pressão.
 * Os três especiais usam sequências distintas para continuarem intencionais
 * tanto no teclado quanto no direcional deslizante do touch.
 */
export const astroRiso: FighterDefinition = {
  id: 'astro-riso',
  name: 'ASTRO RISO',
  archetype: 'SPEED / MIX-UP',
  available: true,
  description: 'Movimento veloz, pressão multi-hit e mudanças rápidas de ritmo.',
  abilities: ['Sorriso Relâmpago', 'Rajada Neon', 'Astro Giro'],
  stats: {
    maxHealth: 930,
    walkSpeed: 3.35,
    backwardSpeed: 2.75,
    jumpSpeed: 15.4,
    jumpForwardSpeed: 3.65,
    jumpBackwardSpeed: 3.15,
    gravity: 0.94,
    weight: 0.84,
    pushbox: { x: -13, y: -52, width: 26, height: 52 },
  },
  standingHurtboxes: STANDING_HURTBOXES,
  crouchingHurtboxes: CROUCHING_HURTBOXES,
  visualHurtboxes: [
    { x: -21, y: -134, width: 42, height: 42, region: 'head' },
    { x: -28, y: -92, width: 56, height: 92, region: 'body' },
  ],
  animations: STANDARD_ANIMATIONS,
  visual: {
    body: 0x356fd1,
    accent: 0x59ecff,
    shadow: 0x38236d,
    skin: 0xc9825e,
  },
  moves: {
    lightPunch: {
      id: 'lightPunch',
      label: 'Soco relâmpago',
      state: 'lightAttack',
      animation: 'standingLight',
      command: { buttons: ['light'], maxGapFrames: 1, bufferFrames: 5, priority: 10 },
      totalFrames: 12,
      hitboxes: [{
        range: { from: 3, to: 5 },
        boxes: [{ id: 'astro-jab', x: 10, y: -53, width: 30, height: 15, kind: 'strike', level: 'high', damage: 38, chipDamage: 0, hitStun: 10, blockStun: 7, hitStop: 4, priority: 1, knockbackX: 1.4, knockbackY: 0 }],
      }],
      meterCost: 0,
      meterGainOnHit: 7,
      meterGainOnBlock: 3,
    },
    heavyPunch: {
      id: 'heavyPunch',
      label: 'Soco estrela',
      state: 'heavyAttack',
      animation: 'standingHeavy',
      command: { buttons: ['heavy'], maxGapFrames: 1, bufferFrames: 6, priority: 9 },
      totalFrames: 24,
      hitboxes: [{
        range: { from: 8, to: 11 },
        boxes: [{ id: 'astro-heavy', x: 8, y: -58, width: 39, height: 21, kind: 'strike', level: 'mid', damage: 74, chipDamage: 4, hitStun: 16, blockStun: 11, hitStop: 7, priority: 2, knockbackX: 2.8, knockbackY: -1 }],
      }],
      meterCost: 0,
      meterGainOnHit: 10,
      meterGainOnBlock: 4,
    },
    lowKick: {
      id: 'lowKick',
      label: 'Chute baixo',
      state: 'kickAttack',
      animation: 'crouchLight',
      command: { directions: ['down'], buttons: ['light'], maxGapFrames: 2, bufferFrames: 5, priority: 14 },
      totalFrames: 18,
      hitboxes: [{
        range: { from: 5, to: 8 },
        boxes: [{ id: 'astro-low', x: 8, y: -20, width: 41, height: 14, kind: 'strike', level: 'low', damage: 45, chipDamage: 2, hitStun: 12, blockStun: 9, hitStop: 5, priority: 1, knockbackX: 1.8, knockbackY: 0 }],
      }],
      hurtboxes: [{ range: { from: 0, to: 18 }, boxes: CROUCHING_HURTBOXES }],
      meterCost: 0,
      meterGainOnHit: 8,
      meterGainOnBlock: 3,
    },
    passoEstelar: {
      id: 'passoEstelar',
      label: 'Passo estelar',
      state: 'lightAttack',
      animation: 'forwardLight',
      command: { directions: ['forward'], buttons: ['light'], maxGapFrames: 2, bufferFrames: 5, priority: 15 },
      totalFrames: 16,
      movement: [{ range: { from: 2, to: 6 }, velocityX: 3.1 }],
      hitboxes: [{
        range: { from: 6, to: 8 },
        boxes: [{ id: 'astro-step', x: 11, y: -52, width: 32, height: 17, kind: 'strike', level: 'high', damage: 48, chipDamage: 2, hitStun: 11, blockStun: 8, hitStop: 4, priority: 1, knockbackX: 1.9, knockbackY: 0 }],
      }],
      meterCost: 0,
      meterGainOnHit: 8,
      meterGainOnBlock: 3,
    },
    rasteira: {
      id: 'rasteira',
      label: 'Rasteira orbital',
      state: 'kickAttack',
      animation: 'crouchHeavy',
      command: { directions: ['down'], buttons: ['heavy'], maxGapFrames: 2, bufferFrames: 5, priority: 16 },
      totalFrames: 26,
      hitboxes: [{
        range: { from: 9, to: 13 },
        boxes: [{ id: 'astro-sweep', x: 7, y: -16, width: 47, height: 16, kind: 'strike', level: 'low', damage: 78, chipDamage: 4, hitStun: 20, blockStun: 13, hitStop: 7, priority: 2, knockbackX: 2.8, knockbackY: -3, knockdown: true }],
      }],
      hurtboxes: [{ range: { from: 0, to: 26 }, boxes: CROUCHING_HURTBOXES }],
      meterCost: 0,
      meterGainOnHit: 11,
      meterGainOnBlock: 4,
    },
    highKick: {
      id: 'highKick',
      label: 'Chute crescente',
      state: 'kickAttack',
      animation: 'forwardHeavy',
      command: { directions: ['forward'], buttons: ['heavy'], maxGapFrames: 2, bufferFrames: 5, priority: 15 },
      totalFrames: 27,
      hitboxes: [{
        range: { from: 9, to: 13 },
        boxes: [{ id: 'astro-high', x: 7, y: -73, width: 47, height: 23, kind: 'strike', level: 'overhead', damage: 88, chipDamage: 5, hitStun: 18, blockStun: 12, hitStop: 8, priority: 3, knockbackX: 3.4, knockbackY: -3.2 }],
      }],
      meterCost: 0,
      meterGainOnHit: 12,
      meterGainOnBlock: 5,
    },
    jumpLightNeutral: {
      id: 'jumpLightNeutral',
      label: 'Soco aéreo',
      state: 'lightAttack',
      animation: 'airLightNeutral',
      air: true,
      jumpTrajectory: 'neutral',
      command: { buttons: ['light'], maxGapFrames: 1, bufferFrames: 5, priority: 20 },
      totalFrames: 18,
      hitboxes: [{
        range: { from: 4, to: 12 },
        boxes: [{ id: 'astro-air-light', x: 7, y: -43, width: 34, height: 27, kind: 'strike', level: 'overhead', damage: 48, chipDamage: 2, hitStun: 11, blockStun: 8, hitStop: 4, priority: 2, knockbackX: 1.6, knockbackY: 0 }],
      }],
      meterCost: 0,
      meterGainOnHit: 7,
      meterGainOnBlock: 3,
    },
    jumpHeavyNeutral: {
      id: 'jumpHeavyNeutral',
      label: 'Chute aéreo',
      state: 'heavyAttack',
      animation: 'airHeavyNeutral',
      air: true,
      jumpTrajectory: 'neutral',
      command: { buttons: ['heavy'], maxGapFrames: 1, bufferFrames: 5, priority: 21 },
      totalFrames: 22,
      hitboxes: [{
        range: { from: 6, to: 14 },
        boxes: [{ id: 'astro-air-heavy', x: 5, y: -48, width: 45, height: 31, kind: 'strike', level: 'overhead', damage: 82, chipDamage: 5, hitStun: 16, blockStun: 11, hitStop: 7, priority: 3, knockbackX: 2.9, knockbackY: -1.8 }],
      }],
      meterCost: 0,
      meterGainOnHit: 10,
      meterGainOnBlock: 4,
    },
    jumpLightForward: {
      id: 'jumpLightForward',
      label: 'Soco aéreo (Frente)',
      state: 'lightAttack',
      animation: 'airLightForward',
      air: true,
      jumpTrajectory: 'forward',
      command: { buttons: ['light'], maxGapFrames: 1, bufferFrames: 5, priority: 22 },
      totalFrames: 18,
      hitboxes: [{
        range: { from: 4, to: 12 },
        boxes: [{ id: 'astro-air-light-fwd', x: 13, y: -40, width: 35, height: 27, kind: 'strike', level: 'overhead', damage: 50, chipDamage: 2, hitStun: 11, blockStun: 8, hitStop: 4, priority: 2, knockbackX: 2.1, knockbackY: 0 }],
      }],
      meterCost: 0,
      meterGainOnHit: 7,
      meterGainOnBlock: 3,
    },
    jumpHeavyForward: {
      id: 'jumpHeavyForward',
      label: 'Chute aéreo (Frente)',
      state: 'heavyAttack',
      animation: 'airHeavyForward',
      air: true,
      jumpTrajectory: 'forward',
      command: { buttons: ['heavy'], maxGapFrames: 1, bufferFrames: 5, priority: 23 },
      totalFrames: 22,
      hitboxes: [{
        range: { from: 6, to: 14 },
        boxes: [{ id: 'astro-air-heavy-fwd', x: 11, y: -44, width: 46, height: 31, kind: 'strike', level: 'overhead', damage: 86, chipDamage: 5, hitStun: 16, blockStun: 11, hitStop: 7, priority: 3, knockbackX: 3.7, knockbackY: -1.8 }],
      }],
      meterCost: 0,
      meterGainOnHit: 10,
      meterGainOnBlock: 4,
    },
    jumpLightBackward: {
      id: 'jumpLightBackward',
      label: 'Soco aéreo (Trás)',
      state: 'lightAttack',
      animation: 'airLightBackward',
      air: true,
      jumpTrajectory: 'backward',
      command: { buttons: ['light'], maxGapFrames: 1, bufferFrames: 5, priority: 22 },
      totalFrames: 18,
      hitboxes: [{
        range: { from: 4, to: 12 },
        boxes: [{ id: 'astro-air-light-back', x: 2, y: -40, width: 34, height: 27, kind: 'strike', level: 'overhead', damage: 46, chipDamage: 2, hitStun: 11, blockStun: 8, hitStop: 4, priority: 2, knockbackX: 1.4, knockbackY: 0 }],
      }],
      meterCost: 0,
      meterGainOnHit: 7,
      meterGainOnBlock: 3,
    },
    jumpHeavyBackward: {
      id: 'jumpHeavyBackward',
      label: 'Chute aéreo (Trás)',
      state: 'heavyAttack',
      animation: 'airHeavyBackward',
      air: true,
      jumpTrajectory: 'backward',
      command: { buttons: ['heavy'], maxGapFrames: 1, bufferFrames: 5, priority: 23 },
      totalFrames: 22,
      hitboxes: [{
        range: { from: 6, to: 14 },
        boxes: [{ id: 'astro-air-heavy-back', x: 0, y: -46, width: 44, height: 31, kind: 'strike', level: 'overhead', damage: 78, chipDamage: 5, hitStun: 15, blockStun: 11, hitStop: 7, priority: 3, knockbackX: 2.3, knockbackY: -1.8 }],
      }],
      meterCost: 0,
      meterGainOnHit: 10,
      meterGainOnBlock: 4,
    },
    sorrisoRelampago: {
      id: 'sorrisoRelampago',
      label: 'Sorriso Relâmpago',
      state: 'specialAttack',
      animation: 'special1',
      command: {
        directions: ['forward', 'down', 'downForward'],
        buttons: ['special'],
        maxGapFrames: 8,
        bufferFrames: 10,
        priority: 92,
      },
      totalFrames: 32,
      movement: [{ range: { from: 4, to: 12 }, velocityX: 7.2 }],
      hitboxes: [{
        range: { from: 11, to: 15 },
        boxes: [{ id: 'astro-sorriso', x: 9, y: -67, width: 57, height: 43, kind: 'strike', level: 'mid', damage: 112, chipDamage: 8, hitStun: 21, blockStun: 15, hitStop: 9, priority: 5, knockbackX: 4.4, knockbackY: -3.4 }],
      }],
      meterCost: 0,
      meterGainOnHit: 15,
      meterGainOnBlock: 7,
      lockFacing: true,
    },
    rajadaNeon: {
      id: 'rajadaNeon',
      label: 'Rajada Neon',
      state: 'specialAttack',
      animation: 'special2',
      command: {
        directions: ['down', 'downForward', 'forward'],
        buttons: ['special'],
        maxGapFrames: 8,
        bufferFrames: 10,
        priority: 90,
      },
      totalFrames: 40,
      hitboxes: [
        { range: { from: 9, to: 11 }, boxes: [{ id: 'astro-rajada-1', x: 8, y: -59, width: 42, height: 23, kind: 'strike', level: 'mid', damage: 34, chipDamage: 2, hitStun: 12, blockStun: 8, hitStop: 4, priority: 4, knockbackX: 0.7, knockbackY: 0 }] },
        { range: { from: 15, to: 17 }, boxes: [{ id: 'astro-rajada-2', x: 10, y: -52, width: 44, height: 22, kind: 'strike', level: 'mid', damage: 32, chipDamage: 2, hitStun: 12, blockStun: 8, hitStop: 4, priority: 4, knockbackX: 0.7, knockbackY: 0 }] },
        { range: { from: 21, to: 23 }, boxes: [{ id: 'astro-rajada-3', x: 9, y: -63, width: 46, height: 24, kind: 'strike', level: 'mid', damage: 32, chipDamage: 2, hitStun: 12, blockStun: 8, hitStop: 4, priority: 4, knockbackX: 0.9, knockbackY: 0 }] },
        { range: { from: 27, to: 30 }, boxes: [{ id: 'astro-rajada-4', x: 8, y: -58, width: 52, height: 30, kind: 'strike', level: 'mid', damage: 42, chipDamage: 4, hitStun: 18, blockStun: 12, hitStop: 7, priority: 5, knockbackX: 5.2, knockbackY: -2.2 }] },
      ],
      meterCost: 0,
      meterGainOnHit: 14,
      meterGainOnBlock: 6,
      lockFacing: true,
    },
    astroGiro: {
      id: 'astroGiro',
      label: 'Astro Giro',
      state: 'specialAttack',
      animation: 'special3',
      command: {
        directions: ['down', 'downBack', 'back'],
        buttons: ['special'],
        maxGapFrames: 8,
        bufferFrames: 10,
        priority: 94,
      },
      totalFrames: 58,
      movement: [{ range: { from: 10, to: 34 }, velocityX: 2.4 }],
      hitboxes: [
        { range: { from: 14, to: 16 }, boxes: [{ id: 'astro-giro-1', x: 5, y: -65, width: 54, height: 45, kind: 'strike', level: 'mid', damage: 45, chipDamage: 4, hitStun: 13, blockStun: 9, hitStop: 5, priority: 7, knockbackX: 0.7, knockbackY: -1 }] },
        { range: { from: 19, to: 21 }, boxes: [{ id: 'astro-giro-2', x: -3, y: -51, width: 58, height: 46, kind: 'strike', level: 'mid', damage: 45, chipDamage: 4, hitStun: 13, blockStun: 9, hitStop: 5, priority: 7, knockbackX: 0.8, knockbackY: -1 }] },
        { range: { from: 24, to: 26 }, boxes: [{ id: 'astro-giro-3', x: 3, y: -72, width: 60, height: 49, kind: 'strike', level: 'mid', damage: 45, chipDamage: 4, hitStun: 13, blockStun: 9, hitStop: 5, priority: 7, knockbackX: 0.9, knockbackY: -1.5 }] },
        { range: { from: 29, to: 31 }, boxes: [{ id: 'astro-giro-4', x: -5, y: -55, width: 61, height: 50, kind: 'strike', level: 'mid', damage: 45, chipDamage: 4, hitStun: 13, blockStun: 9, hitStop: 5, priority: 7, knockbackX: 1, knockbackY: -2 }] },
        { range: { from: 34, to: 37 }, boxes: [{ id: 'astro-giro-5', x: 7, y: -77, width: 65, height: 52, kind: 'strike', level: 'overhead', damage: 65, chipDamage: 7, hitStun: 27, blockStun: 17, hitStop: 12, priority: 9, knockbackX: 6.4, knockbackY: -8, knockdown: true }] },
      ],
      meterCost: 100,
      meterGainOnHit: 0,
      meterGainOnBlock: 0,
      isSuper: true,
      cinematic: 'rush',
      lockFacing: true,
    },
  },
};
