import type { FighterDefinition } from '../types/combat';
import { CROUCHING_HURTBOXES, STANDARD_ANIMATIONS, STANDING_HURTBOXES } from './shared';

/**
 * Bomba de Fumaça: redução 0.70 por 120 frames; cooldown total 210 (120 ativos + 90)
 * evita manutenção quase permanente do buff sem custo de energia.
 */
const BOMBA_FUMACA_DURATION = 120;
const BOMBA_FUMACA_COOLDOWN = 210;
const BOMBA_FUMACA_MULTIPLIER = 0.7;

export const danteSinal: FighterDefinition = {
  id: 'dante-sinal',
  name: 'DANTE SINAL',
  archetype: 'TECHNICAL / ZONER',
  available: true,
  description: 'Controle de espaço, zoning e precisão no posicionamento.',
  abilities: ['Ponto Final', 'Bomba de Fumaça', 'Chave Binária'],
  stats: {
    maxHealth: 960,
    walkSpeed: 2.85,
    backwardSpeed: 2.65,
    jumpSpeed: 14.8,
    jumpForwardSpeed: 3.05,
    jumpBackwardSpeed: 2.85,
    gravity: 0.94,
    weight: 0.95,
    pushbox: { x: -14, y: -54, width: 28, height: 54 },
  },
  standingHurtboxes: STANDING_HURTBOXES,
  crouchingHurtboxes: CROUCHING_HURTBOXES,
  // Espaço visual usado pelos agarrões de Guto (usesVisualHurtboxes).
  visualHurtboxes: [
    { x: -22, y: -136, width: 44, height: 44, region: 'head' },
    { x: -30, y: -94, width: 60, height: 94, region: 'body' },
  ],
  animations: STANDARD_ANIMATIONS,
  visual: { body: 0x405e78, accent: 0x70ffbf, shadow: 0x172534, skin: 0xba795d },
  projectiles: {
    chaveBinaria: {
      id: 'chave-binaria-hazard',
      offsetX: 45,
      offsetY: -54,
      velocityX: 5,
      lifeFrames: 120,
      armingFrames: 0,
      spawnMode: 'ownerOffset',
      maxActivePerOwner: 1,
      hitbox: {
        // y/height: faixa mid ~Y mundo 242–258 com projétil em GROUND_Y-54.
        id: 'chave-binaria-hit',
        x: -14,
        y: -8,
        width: 28,
        height: 16,
        kind: 'projectile',
        level: 'mid',
        damage: 65,
        chipDamage: 4,
        hitStun: 18,
        blockStun: 12,
        hitStop: 7,
        priority: 10,
        knockbackX: 2.5,
        knockbackY: 0,
      },
    },
    pontoFinal: {
      id: 'ponto-final-hazard',
      offsetX: 0,
      offsetY: 0,
      velocityX: 0,
      // arming 42 + 5 frames ativos de explosão
      lifeFrames: 47,
      armingFrames: 42,
      spawnMode: 'targetSnapshot',
      maxActivePerOwner: 1,
      hitbox: {
        id: 'ponto-final-hit',
        x: -24,
        y: -80,
        width: 48,
        height: 80,
        kind: 'projectile',
        level: 'mid',
        damage: 240,
        chipDamage: 25,
        hitStun: 35,
        blockStun: 22,
        hitStop: 20,
        priority: 20,
        knockbackX: 6,
        knockbackY: -8,
        knockdown: true,
      },
    },
  },
  moves: {
    lightPunch: {
      id: 'lightPunch',
      label: 'Soco rápido',
      state: 'lightAttack',
      animation: 'standingLight',
      command: { buttons: ['light'], maxGapFrames: 1, bufferFrames: 5, priority: 10 },
      totalFrames: 16,
      hitboxes: [{
        range: { from: 5, to: 7 },
        boxes: [{ id: 'dante-jab', x: 10, y: -54, width: 29, height: 15, kind: 'strike', level: 'high', damage: 45, chipDamage: 0, hitStun: 11, blockStun: 8, hitStop: 5, priority: 1, knockbackX: 1.6, knockbackY: 0 }],
      }],
      cancels: [{ range: { from: 8, to: 12 }, into: ['bombaFumaca', 'chaveBinaria'], condition: 'hit' }],
      meterCost: 0,
      meterGainOnHit: 8,
      meterGainOnBlock: 3,
    },
    heavyPunch: {
      id: 'heavyPunch',
      label: 'Soco forte',
      state: 'heavyAttack',
      animation: 'standingHeavy',
      command: { buttons: ['heavy'], maxGapFrames: 1, bufferFrames: 6, priority: 9 },
      totalFrames: 30,
      hitboxes: [{
        range: { from: 11, to: 14 },
        boxes: [{ id: 'dante-heavy', x: 7, y: -58, width: 40, height: 22, kind: 'strike', level: 'mid', damage: 85, chipDamage: 5, hitStun: 18, blockStun: 13, hitStop: 8, priority: 2, knockbackX: 3.3, knockbackY: -1 }],
      }],
      meterCost: 0,
      meterGainOnHit: 12,
      meterGainOnBlock: 5,
    },
    lowKick: {
      id: 'lowKick',
      label: 'Chute baixo',
      state: 'kickAttack',
      animation: 'crouchLight',
      command: { directions: ['down'], buttons: ['light'], maxGapFrames: 2, bufferFrames: 5, priority: 14 },
      totalFrames: 30,
      hitboxes: [{
        range: { from: 11, to: 14 },
        boxes: [{
          id: 'dante-low',
          x: 8,
          y: -18,
          width: 48,
          height: 16,
          kind: 'strike',
          level: 'low',
          damage: 55,
          chipDamage: 2,
          hitStun: 14,
          blockStun: 10,
          hitStop: 6,
          priority: 1,
          knockbackX: 2.1,
          knockbackY: 0,
        }],
      }],
      hurtboxes: [{ range: { from: 0, to: 29 }, boxes: CROUCHING_HURTBOXES }],
      meterCost: 0,
      meterGainOnHit: 9,
      meterGainOnBlock: 4,
    },
    avancoLeve: {
      id: 'avancoLeve',
      label: 'Golpe avançando',
      state: 'lightAttack',
      animation: 'forwardLight',
      command: { directions: ['forward'], buttons: ['light'], maxGapFrames: 2, bufferFrames: 5, priority: 15 },
      totalFrames: 20,
      movement: [{ range: { from: 4, to: 9 }, velocityX: 2.7 }],
      hitboxes: [{
        range: { from: 9, to: 12 },
        boxes: [{ id: 'dante-advance', x: 10, y: -56, width: 32, height: 16, kind: 'strike', level: 'high', damage: 55, chipDamage: 2, hitStun: 12, blockStun: 9, hitStop: 5, priority: 1, knockbackX: 2, knockbackY: 0 }],
      }],
      meterCost: 0,
      meterGainOnHit: 9,
      meterGainOnBlock: 4,
    },
    rasteira: {
      id: 'rasteira',
      label: 'Rasteira',
      state: 'kickAttack',
      animation: 'crouchHeavy',
      command: { directions: ['down'], buttons: ['heavy'], maxGapFrames: 2, bufferFrames: 5, priority: 16 },
      totalFrames: 38,
      hitboxes: [{
        range: { from: 14, to: 19 },
        boxes: [{
          id: 'dante-sweep',
          x: 6,
          y: -14,
          width: 54,
          height: 14,
          kind: 'strike',
          level: 'low',
          damage: 90,
          chipDamage: 5,
          hitStun: 22,
          blockStun: 14,
          hitStop: 8,
          priority: 2,
          knockbackX: 3,
          knockbackY: -3,
          knockdown: true,
        }],
      }],
      hurtboxes: [{ range: { from: 0, to: 37 }, boxes: CROUCHING_HURTBOXES }],
      meterCost: 0,
      meterGainOnHit: 12,
      meterGainOnBlock: 5,
    },
    highKick: {
      id: 'highKick',
      label: 'Chute de alcance',
      state: 'kickAttack',
      animation: 'forwardHeavy',
      command: { directions: ['forward'], buttons: ['heavy'], maxGapFrames: 2, bufferFrames: 5, priority: 15 },
      totalFrames: 33,
      hitboxes: [{
        range: { from: 13, to: 17 },
        boxes: [{ id: 'dante-high', x: 5, y: -76, width: 48, height: 24, kind: 'strike', level: 'overhead', damage: 100, chipDamage: 6, hitStun: 20, blockStun: 14, hitStop: 9, priority: 3, knockbackX: 3.8, knockbackY: -3.6 }],
      }],
      meterCost: 0,
      meterGainOnHit: 14,
      meterGainOnBlock: 6,
    },
    jumpLightNeutral: {
      id: 'jumpLightNeutral',
      label: 'Soco aéreo',
      state: 'lightAttack',
      animation: 'airLightNeutral',
      air: true,
      jumpTrajectory: 'neutral',
      command: { buttons: ['light'], maxGapFrames: 1, bufferFrames: 5, priority: 20 },
      totalFrames: 23,
      hitboxes: [{
        range: { from: 6, to: 15 },
        boxes: [{ id: 'dante-air-light', x: 6, y: -44, width: 34, height: 28, kind: 'strike', level: 'overhead', damage: 55, chipDamage: 3, hitStun: 13, blockStun: 9, hitStop: 5, priority: 2, knockbackX: 1.8, knockbackY: 0 }],
      }],
      meterCost: 0,
      meterGainOnHit: 8,
      meterGainOnBlock: 3,
    },
    jumpHeavyNeutral: {
      id: 'jumpHeavyNeutral',
      label: 'Chute aéreo',
      state: 'heavyAttack',
      animation: 'airHeavyNeutral',
      air: true,
      jumpTrajectory: 'neutral',
      command: { buttons: ['heavy'], maxGapFrames: 1, bufferFrames: 5, priority: 21 },
      totalFrames: 27,
      hitboxes: [{
        range: { from: 8, to: 17 },
        boxes: [{ id: 'dante-air-kick', x: 4, y: -50, width: 44, height: 32, kind: 'strike', level: 'overhead', damage: 95, chipDamage: 6, hitStun: 18, blockStun: 12, hitStop: 8, priority: 3, knockbackX: 3.2, knockbackY: -2 }],
      }],
      meterCost: 0,
      meterGainOnHit: 12,
      meterGainOnBlock: 5,
    },
    jumpLightForward: {
      id: 'jumpLightForward',
      label: 'Soco aéreo (Frente)',
      state: 'lightAttack',
      animation: 'airLightForward',
      air: true,
      jumpTrajectory: 'forward',
      command: { buttons: ['light'], maxGapFrames: 1, bufferFrames: 5, priority: 22 },
      totalFrames: 23,
      hitboxes: [{
        range: { from: 6, to: 15 },
        boxes: [{ id: 'dante-air-light-fwd', x: 12, y: -40, width: 34, height: 28, kind: 'strike', level: 'overhead', damage: 60, chipDamage: 3, hitStun: 13, blockStun: 9, hitStop: 5, priority: 2, knockbackX: 2.2, knockbackY: 0 }],
      }],
      meterCost: 0,
      meterGainOnHit: 8,
      meterGainOnBlock: 3,
    },
    jumpHeavyForward: {
      id: 'jumpHeavyForward',
      label: 'Chute aéreo (Frente)',
      state: 'heavyAttack',
      animation: 'airHeavyForward',
      air: true,
      jumpTrajectory: 'forward',
      command: { buttons: ['heavy'], maxGapFrames: 1, bufferFrames: 5, priority: 23 },
      totalFrames: 27,
      hitboxes: [{
        range: { from: 8, to: 17 },
        boxes: [{ id: 'dante-air-kick-fwd', x: 10, y: -45, width: 44, height: 32, kind: 'strike', level: 'overhead', damage: 100, chipDamage: 6, hitStun: 18, blockStun: 12, hitStop: 8, priority: 3, knockbackX: 4.0, knockbackY: -2 }],
      }],
      meterCost: 0,
      meterGainOnHit: 12,
      meterGainOnBlock: 5,
    },
    jumpLightBackward: {
      id: 'jumpLightBackward',
      label: 'Soco aéreo (Trás)',
      state: 'lightAttack',
      animation: 'airLightBackward',
      air: true,
      jumpTrajectory: 'backward',
      command: { buttons: ['light'], maxGapFrames: 1, bufferFrames: 5, priority: 22 },
      totalFrames: 23,
      hitboxes: [{
        range: { from: 6, to: 15 },
        boxes: [{ id: 'dante-air-light-back', x: 2, y: -40, width: 34, height: 28, kind: 'strike', level: 'overhead', damage: 55, chipDamage: 3, hitStun: 13, blockStun: 9, hitStop: 5, priority: 2, knockbackX: 1.5, knockbackY: 0 }],
      }],
      meterCost: 0,
      meterGainOnHit: 8,
      meterGainOnBlock: 3,
    },
    jumpHeavyBackward: {
      id: 'jumpHeavyBackward',
      label: 'Chute aéreo (Trás)',
      state: 'heavyAttack',
      animation: 'airHeavyBackward',
      air: true,
      jumpTrajectory: 'backward',
      command: { buttons: ['heavy'], maxGapFrames: 1, bufferFrames: 5, priority: 23 },
      totalFrames: 27,
      hitboxes: [{
        range: { from: 8, to: 17 },
        boxes: [{ id: 'dante-air-kick-back', x: 0, y: -45, width: 44, height: 32, kind: 'strike', level: 'overhead', damage: 90, chipDamage: 6, hitStun: 18, blockStun: 12, hitStop: 8, priority: 3, knockbackX: 2.5, knockbackY: -2 }],
      }],
      meterCost: 0,
      meterGainOnHit: 12,
      meterGainOnBlock: 5,
    },

    bombaFumaca: {
      id: 'bombaFumaca',
      label: 'Bomba de Fumaça',
      state: 'specialAttack',
      animation: 'special2',
      command: { directions: ['down', 'downForward', 'forward'], buttons: ['special'], maxGapFrames: 8, bufferFrames: 10, priority: 30 },
      totalFrames: 40,
      hitboxes: [],
      // Abertura da fumaça legível: redução só no evento (frame 12), não no frame 0.
      events: [{
        frame: 12,
        type: 'grantDamageReduction',
        durationFrames: BOMBA_FUMACA_DURATION,
        multiplier: BOMBA_FUMACA_MULTIPLIER,
        cooldownFrames: BOMBA_FUMACA_COOLDOWN,
      }],
      meterCost: 0,
      meterGainOnHit: 0,
      meterGainOnBlock: 0,
    },
    chaveBinaria: {
      id: 'chaveBinaria',
      label: 'Chave Binária',
      state: 'specialAttack',
      animation: 'special1',
      command: { directions: ['down', 'downBack', 'back'], buttons: ['special'], maxGapFrames: 8, bufferFrames: 10, priority: 30 },
      totalFrames: 42,
      hitboxes: [],
      events: [{ frame: 14, type: 'spawnProjectile', projectileId: 'chave-binaria-hazard' }],
      meterCost: 0,
      meterGainOnHit: 10,
      meterGainOnBlock: 5,
    },
    pontoFinal: {
      id: 'pontoFinal',
      label: 'Ponto Final',
      state: 'specialAttack',
      animation: 'special3',
      command: { directions: ['forward', 'down', 'downForward'], buttons: ['special'], maxGapFrames: 8, bufferFrames: 10, priority: 50 },
      totalFrames: 60,
      hitboxes: [],
      events: [{ frame: 5, type: 'spawnProjectile', projectileId: 'ponto-final-hazard' }],
      meterCost: 100,
      meterGainOnHit: 0,
      meterGainOnBlock: 0,
      isSuper: true,
      lockFacing: true,
    },
  },
};

export const DANTE_BOMBA_FUMACA = {
  durationFrames: BOMBA_FUMACA_DURATION,
  cooldownFrames: BOMBA_FUMACA_COOLDOWN,
  multiplier: BOMBA_FUMACA_MULTIPLIER,
} as const;
