import type { FighterDefinition } from '../types/combat';
import { CROUCHING_HURTBOXES, STANDARD_ANIMATIONS } from './shared';

export const gutoBarba: FighterDefinition = {
  id: 'guto-barba',
  name: 'GUTO BARBA',
  archetype: 'TANK / GRAPPLER',
  available: true,
  description: 'Passos firmes, golpes devastadores e agarrões curtos.',
  abilities: ['Muralha Norte', 'Gancho do Urso', 'Abraço Glacial'],
  stats: {
    maxHealth: 1250,
    walkSpeed: 1.75,
    backwardSpeed: 1.45,
    jumpSpeed: 6.4,
    gravity: 0.43,
    weight: 1.28,
    pushbox: { x: -19, y: -61, width: 38, height: 61 },
  },
  standingHurtboxes: [
    { x: -15, y: -75, width: 30, height: 23, region: 'head' },
    { x: -21, y: -53, width: 42, height: 35, region: 'body' },
    { x: -18, y: -20, width: 36, height: 20, region: 'legs' },
  ],
  crouchingHurtboxes: CROUCHING_HURTBOXES,
  animations: STANDARD_ANIMATIONS,
  visual: {
    body: 0x61488e,
    accent: 0xa8e9ff,
    shadow: 0x2a2144,
    skin: 0xad7658,
  },
  moves: {
    elbow: {
      id: 'elbow',
      label: 'Cotovelada',
      state: 'lightAttack',
      animation: 'attack',
      command: { buttons: ['light'], maxGapFrames: 1, bufferFrames: 5, priority: 10 },
      totalFrames: 20,
      hitboxes: [{
        range: { from: 6, to: 9 },
        boxes: [{ id: 'guto-elbow', x: 8, y: -58, width: 34, height: 22, kind: 'strike', level: 'mid', damage: 66, chipDamage: 2, hitStun: 15, blockStun: 10, hitStop: 7, priority: 2, knockbackX: 2.2, knockbackY: 0 }],
      }],
      meterCost: 0,
      meterGainOnHit: 9,
      meterGainOnBlock: 4,
    },
    heavyPunch: {
      id: 'heavyPunch',
      label: 'Soco pesado',
      state: 'heavyAttack',
      animation: 'attack',
      command: { buttons: ['heavy'], maxGapFrames: 1, bufferFrames: 6, priority: 9 },
      totalFrames: 36,
      hitboxes: [{
        range: { from: 14, to: 18 },
        boxes: [{ id: 'guto-heavy', x: 6, y: -65, width: 51, height: 28, kind: 'strike', level: 'mid', damage: 122, chipDamage: 8, hitStun: 23, blockStun: 16, hitStop: 11, priority: 4, knockbackX: 5, knockbackY: -1.2, knockdown: true }],
      }],
      meterCost: 0,
      meterGainOnHit: 15,
      meterGainOnBlock: 7,
    },
    frontKick: {
      id: 'frontKick',
      label: 'Chute frontal',
      state: 'kickAttack',
      animation: 'attack',
      command: { directions: ['down'], buttons: ['light'], maxGapFrames: 2, bufferFrames: 5, priority: 14 },
      totalFrames: 29,
      hitboxes: [{
        range: { from: 10, to: 14 },
        boxes: [{ id: 'guto-front-kick', x: 8, y: -35, width: 48, height: 22, kind: 'strike', level: 'low', damage: 82, chipDamage: 4, hitStun: 17, blockStun: 12, hitStop: 8, priority: 3, knockbackX: 3.3, knockbackY: 0 }],
      }],
      meterCost: 0,
      meterGainOnHit: 11,
      meterGainOnBlock: 5,
    },
    descendingBlow: {
      id: 'descendingBlow',
      label: 'Golpe descendente',
      state: 'kickAttack',
      animation: 'attack',
      command: { directions: ['forward'], buttons: ['heavy'], maxGapFrames: 2, bufferFrames: 5, priority: 15 },
      totalFrames: 40,
      hitboxes: [{
        range: { from: 17, to: 21 },
        boxes: [{ id: 'guto-overhead', x: 1, y: -85, width: 48, height: 55, kind: 'strike', level: 'overhead', damage: 138, chipDamage: 9, hitStun: 25, blockStun: 17, hitStop: 12, priority: 5, knockbackX: 5.5, knockbackY: -3.2, knockdown: true }],
      }],
      meterCost: 0,
      meterGainOnHit: 16,
      meterGainOnBlock: 8,
    },
    muralhaNorte: {
      id: 'muralhaNorte',
      label: 'Muralha Norte',
      state: 'specialAttack',
      animation: 'attack',
      command: { buttons: ['special'], maxGapFrames: 2, bufferFrames: 7, priority: 30 },
      totalFrames: 52,
      movement: [{ range: { from: 7, to: 35 }, velocityX: 1.8 }],
      hitboxes: [{
        range: { from: 20, to: 31 },
        boxes: [{ id: 'guto-wall', x: 12, y: -63, width: 39, height: 55, kind: 'strike', level: 'mid', damage: 104, chipDamage: 10, hitStun: 20, blockStun: 17, hitStop: 9, priority: 5, knockbackX: 4.2, knockbackY: 0 }],
      }],
      events: [{ frame: 4, type: 'grantArmor', hits: 1 }, { frame: 36, type: 'clearArmor' }],
      meterCost: 0,
      meterGainOnHit: 15,
      meterGainOnBlock: 8,
      lockFacing: true,
    },
    ganchoUrso: {
      id: 'ganchoUrso',
      label: 'Gancho do Urso',
      state: 'specialAttack',
      animation: 'attack',
      command: { directions: ['forward'], buttons: ['light', 'heavy'], maxGapFrames: 3, bufferFrames: 6, priority: 40 },
      totalFrames: 43,
      hitboxes: [{
        range: { from: 9, to: 11 },
        boxes: [{ id: 'guto-throw', x: 5, y: -62, width: 31, height: 55, kind: 'throw', level: 'mid', damage: 155, chipDamage: 0, hitStun: 28, blockStun: 0, hitStop: 12, priority: 7, knockbackX: 4.5, knockbackY: -5, knockdown: true }],
      }],
      meterCost: 0,
      meterGainOnHit: 18,
      meterGainOnBlock: 0,
      lockFacing: true,
    },
    abracoGlacial: {
      id: 'abracoGlacial',
      label: 'Abraço Glacial',
      state: 'specialAttack',
      animation: 'attack',
      command: { directions: ['down', 'downForward', 'forward'], buttons: ['heavy', 'special'], maxGapFrames: 9, bufferFrames: 8, priority: 60 },
      totalFrames: 64,
      movement: [{ range: { from: 7, to: 14 }, velocityX: 2.5 }],
      hitboxes: [{
        range: { from: 15, to: 18 },
        boxes: [{ id: 'guto-super-throw', x: 2, y: -69, width: 36, height: 66, kind: 'throw', level: 'mid', damage: 280, chipDamage: 0, hitStun: 52, blockStun: 0, hitStop: 24, priority: 10, knockbackX: 3.2, knockbackY: -6.5, knockdown: true, freezeFrames: 40 }],
      }],
      meterCost: 100,
      meterGainOnHit: 0,
      meterGainOnBlock: 0,
      isSuper: true,
      cinematic: 'freeze',
      lockFacing: true,
    },
  },
};
