import type { FighterDefinition } from '../types/combat';
import { CROUCHING_HURTBOXES, STANDARD_ANIMATIONS } from './shared';

export const gutoBarba: FighterDefinition = {
  id: 'guto-barba',
  name: 'GUTO BARBA',
  archetype: 'TANK / GRAPPLER',
  available: true,
  description: 'Passos firmes, golpes devastadores e agarrões curtos.',
  abilities: ['Muralha Norte', 'Gancho do Urso', 'Abraço Glacial'],
  stats: {
    maxHealth: 1250,
    walkSpeed: 1.75,
    backwardSpeed: 1.45,
    // Velocidades/aceleração verticais na escala do mundo 640x360
    // (dobradas na migração de 320x180; o tempo de voo não muda).
    jumpSpeed: 12.8,
    // Pulo diagonal curto e pesado (arquétipo tanque).
    jumpForwardSpeed: 1.9,
    jumpBackwardSpeed: 1.7,
    gravity: 0.86,
    weight: 1.28,
    pushbox: { x: -19, y: -61, width: 38, height: 61 },
  },
  standingHurtboxes: [
    { x: -15, y: -75, width: 30, height: 23, region: 'head' },
    { x: -21, y: -53, width: 42, height: 35, region: 'body' },
    { x: -18, y: -20, width: 36, height: 20, region: 'legs' },
  ],
  crouchingHurtboxes: CROUCHING_HURTBOXES,
  animations: STANDARD_ANIMATIONS,
  visual: {
    body: 0x61488e,
    accent: 0xa8e9ff,
    shadow: 0x2a2144,
    skin: 0xad7658,
  },
  moves: {
    elbow: {
      id: 'elbow',
      label: 'Cotovelada',
      state: 'lightAttack',
      animation: 'attack',
      command: { buttons: ['light'], maxGapFrames: 1, bufferFrames: 5, priority: 10 },
      totalFrames: 20,
      hitboxes: [{
        range: { from: 6, to: 9 },
        boxes: [{ id: 'guto-elbow', x: 8, y: -58, width: 34, height: 22, kind: 'strike', level: 'mid', damage: 66, chipDamage: 2, hitStun: 15, blockStun: 10, hitStop: 7, priority: 2, knockbackX: 2.2, knockbackY: 0 }],
      }],
      meterCost: 0,
      meterGainOnHit: 9,
      meterGainOnBlock: 4,
    },
    heavyPunch: {
      id: 'heavyPunch',
      label: 'Soco pesado',
      state: 'heavyAttack',
      animation: 'attack',
      command: { buttons: ['heavy'], maxGapFrames: 1, bufferFrames: 6, priority: 9 },
      totalFrames: 36,
      hitboxes: [{
        range: { from: 14, to: 18 },
        boxes: [{ id: 'guto-heavy', x: 6, y: -65, width: 51, height: 28, kind: 'strike', level: 'mid', damage: 122, chipDamage: 8, hitStun: 23, blockStun: 16, hitStop: 11, priority: 4, knockbackX: 5, knockbackY: -2.4, knockdown: true }],
      }],
      meterCost: 0,
      meterGainOnHit: 15,
      meterGainOnBlock: 7,
    },
    frontKick: {
      id: 'frontKick',
      label: 'Chute frontal',
      state: 'kickAttack',
      animation: 'attack',
      command: { directions: ['down'], buttons: ['light'], maxGapFrames: 2, bufferFrames: 5, priority: 14 },
      totalFrames: 29,
      hitboxes: [{
        range: { from: 10, to: 14 },
        boxes: [{ id: 'guto-front-kick', x: 8, y: -35, width: 48, height: 22, kind: 'strike', level: 'low', damage: 82, chipDamage: 4, hitStun: 17, blockStun: 12, hitStop: 8, priority: 3, knockbackX: 3.3, knockbackY: 0 }],
      }],
      hurtboxes: [{ range: { from: 0, to: 29 }, boxes: CROUCHING_HURTBOXES }],
      meterCost: 0,
      meterGainOnHit: 11,
      meterGainOnBlock: 5,
    },
    ombrada: {
      id: 'ombrada',
      label: 'Ombrada',
      state: 'lightAttack',
      animation: 'attack',
      command: { directions: ['forward'], buttons: ['light'], maxGapFrames: 2, bufferFrames: 5, priority: 15 },
      totalFrames: 23,
      movement: [{ range: { from: 4, to: 10 }, velocityX: 2 }],
      hitboxes: [{
        range: { from: 9, to: 12 },
        boxes: [{ id: 'guto-shoulder', x: 8, y: -60, width: 36, height: 24, kind: 'strike', level: 'mid', damage: 72, chipDamage: 3, hitStun: 15, blockStun: 11, hitStop: 7, priority: 2, knockbackX: 2.6, knockbackY: 0 }],
      }],
      meterCost: 0,
      meterGainOnHit: 10,
      meterGainOnBlock: 4,
    },
    rasteiraUrso: {
      id: 'rasteiraUrso',
      label: 'Rasteira do Urso',
      state: 'kickAttack',
      animation: 'attack',
      command: { directions: ['down'], buttons: ['heavy'], maxGapFrames: 2, bufferFrames: 5, priority: 16 },
      totalFrames: 36,
      hitboxes: [{
        range: { from: 14, to: 18 },
        boxes: [{ id: 'guto-sweep', x: 6, y: -18, width: 50, height: 18, kind: 'strike', level: 'low', damage: 118, chipDamage: 7, hitStun: 24, blockStun: 15, hitStop: 10, priority: 3, knockbackX: 3.4, knockbackY: -3.4, knockdown: true }],
      }],
      hurtboxes: [{ range: { from: 0, to: 36 }, boxes: CROUCHING_HURTBOXES }],
      meterCost: 0,
      meterGainOnHit: 14,
      meterGainOnBlock: 6,
    },
    jumpLightNeutral: {
      id: 'jumpLightNeutral',
      label: 'Soco aéreo',
      state: 'lightAttack',
      animation: 'attack',
      air: true,
      jumpTrajectory: 'neutral',
      command: { buttons: ['light'], maxGapFrames: 1, bufferFrames: 5, priority: 20 },
      totalFrames: 24,
      hitboxes: [{
        range: { from: 6, to: 15 },
        boxes: [{ id: 'guto-air-light', x: 6, y: -48, width: 38, height: 30, kind: 'strike', level: 'overhead', damage: 72, chipDamage: 4, hitStun: 15, blockStun: 10, hitStop: 6, priority: 2, knockbackX: 2.2, knockbackY: 0 }],
      }],
      meterCost: 0,
      meterGainOnHit: 9,
      meterGainOnBlock: 4,
    },
    jumpHeavyNeutral: {
      id: 'jumpHeavyNeutral',
      label: 'Chute aéreo',
      state: 'heavyAttack',
      animation: 'attack',
      air: true,
      jumpTrajectory: 'neutral',
      command: { buttons: ['heavy'], maxGapFrames: 1, bufferFrames: 5, priority: 21 },
      totalFrames: 28,
      hitboxes: [{
        range: { from: 8, to: 17 },
        boxes: [{ id: 'guto-air-kick', x: 4, y: -54, width: 48, height: 34, kind: 'strike', level: 'overhead', damage: 120, chipDamage: 8, hitStun: 20, blockStun: 13, hitStop: 9, priority: 3, knockbackX: 3.6, knockbackY: -2.5 }],
      }],
      meterCost: 0,
      meterGainOnHit: 14,
      meterGainOnBlock: 6,
    },
    jumpLightForward: {
      id: 'jumpLightForward',
      label: 'Soco aéreo (Frente)',
      state: 'lightAttack',
      animation: 'attack',
      air: true,
      jumpTrajectory: 'forward',
      command: { buttons: ['light'], maxGapFrames: 1, bufferFrames: 5, priority: 22 },
      totalFrames: 24,
      hitboxes: [{
        range: { from: 6, to: 15 },
        boxes: [{ id: 'guto-air-light-fwd', x: 12, y: -44, width: 38, height: 30, kind: 'strike', level: 'overhead', damage: 75, chipDamage: 4, hitStun: 15, blockStun: 10, hitStop: 6, priority: 2, knockbackX: 2.8, knockbackY: 0 }],
      }],
      meterCost: 0,
      meterGainOnHit: 9,
      meterGainOnBlock: 4,
    },
    jumpHeavyForward: {
      id: 'jumpHeavyForward',
      label: 'Chute aéreo (Frente)',
      state: 'heavyAttack',
      animation: 'attack',
      air: true,
      jumpTrajectory: 'forward',
      command: { buttons: ['heavy'], maxGapFrames: 1, bufferFrames: 5, priority: 23 },
      totalFrames: 28,
      hitboxes: [{
        range: { from: 8, to: 17 },
        boxes: [{ id: 'guto-air-kick-fwd', x: 10, y: -50, width: 48, height: 34, kind: 'strike', level: 'overhead', damage: 125, chipDamage: 8, hitStun: 20, blockStun: 13, hitStop: 9, priority: 3, knockbackX: 4.5, knockbackY: -2.5 }],
      }],
      meterCost: 0,
      meterGainOnHit: 14,
      meterGainOnBlock: 6,
    },
    jumpLightBackward: {
      id: 'jumpLightBackward',
      label: 'Soco aéreo (Trás)',
      state: 'lightAttack',
      animation: 'attack',
      air: true,
      jumpTrajectory: 'backward',
      command: { buttons: ['light'], maxGapFrames: 1, bufferFrames: 5, priority: 22 },
      totalFrames: 24,
      hitboxes: [{
        range: { from: 6, to: 15 },
        boxes: [{ id: 'guto-air-light-back', x: 2, y: -44, width: 38, height: 30, kind: 'strike', level: 'overhead', damage: 70, chipDamage: 4, hitStun: 15, blockStun: 10, hitStop: 6, priority: 2, knockbackX: 1.8, knockbackY: 0 }],
      }],
      meterCost: 0,
      meterGainOnHit: 9,
      meterGainOnBlock: 4,
    },
    jumpHeavyBackward: {
      id: 'jumpHeavyBackward',
      label: 'Chute aéreo (Trás)',
      state: 'heavyAttack',
      animation: 'attack',
      air: true,
      jumpTrajectory: 'backward',
      command: { buttons: ['heavy'], maxGapFrames: 1, bufferFrames: 5, priority: 23 },
      totalFrames: 28,
      hitboxes: [{
        range: { from: 8, to: 17 },
        boxes: [{ id: 'guto-air-kick-back', x: 0, y: -50, width: 48, height: 34, kind: 'strike', level: 'overhead', damage: 115, chipDamage: 8, hitStun: 20, blockStun: 13, hitStop: 9, priority: 3, knockbackX: 3.0, knockbackY: -2.5 }],
      }],
      meterCost: 0,
      meterGainOnHit: 14,
      meterGainOnBlock: 6,
    },
    descendingBlow: {
      id: 'descendingBlow',
      label: 'Golpe descendente',
      state: 'kickAttack',
      animation: 'attack',
      command: { directions: ['forward'], buttons: ['heavy'], maxGapFrames: 2, bufferFrames: 5, priority: 15 },
      totalFrames: 40,
      hitboxes: [{
        range: { from: 17, to: 21 },
        boxes: [{ id: 'guto-overhead', x: 1, y: -85, width: 48, height: 55, kind: 'strike', level: 'overhead', damage: 138, chipDamage: 9, hitStun: 25, blockStun: 17, hitStop: 12, priority: 5, knockbackX: 5.5, knockbackY: -6.4, knockdown: true }],
      }],
      meterCost: 0,
      meterGainOnHit: 16,
      meterGainOnBlock: 8,
    },
    muralhaNorte: {
      id: 'muralhaNorte',
      label: 'Muralha Norte',
      state: 'specialAttack',
      animation: 'attack',
      command: { buttons: ['special'], maxGapFrames: 2, bufferFrames: 7, priority: 30 },
      totalFrames: 52,
      movement: [{ range: { from: 7, to: 35 }, velocityX: 1.8 }],
      hitboxes: [{
        range: { from: 20, to: 31 },
        boxes: [{ id: 'guto-wall', x: 12, y: -63, width: 39, height: 55, kind: 'strike', level: 'mid', damage: 104, chipDamage: 10, hitStun: 20, blockStun: 17, hitStop: 9, priority: 5, knockbackX: 4.2, knockbackY: 0 }],
      }],
      events: [{ frame: 4, type: 'grantArmor', hits: 1 }, { frame: 36, type: 'clearArmor' }],
      meterCost: 0,
      meterGainOnHit: 15,
      meterGainOnBlock: 8,
      lockFacing: true,
    },
    ganchoUrso: {
      id: 'ganchoUrso',
      label: 'Gancho do Urso',
      state: 'specialAttack',
      animation: 'attack',
      command: { directions: ['forward'], buttons: ['light', 'heavy'], maxGapFrames: 3, bufferFrames: 6, priority: 40 },
      totalFrames: 43,
      hitboxes: [{
        range: { from: 9, to: 11 },
        boxes: [{ id: 'guto-throw', x: 5, y: -62, width: 31, height: 55, kind: 'throw', level: 'mid', damage: 155, chipDamage: 0, hitStun: 28, blockStun: 0, hitStop: 12, priority: 7, knockbackX: 4.5, knockbackY: -10, knockdown: true }],
      }],
      meterCost: 0,
      meterGainOnHit: 18,
      meterGainOnBlock: 0,
      lockFacing: true,
    },
    abracoGlacial: {
      id: 'abracoGlacial',
      label: 'Abraço Glacial',
      state: 'specialAttack',
      animation: 'attack',
      command: { directions: ['down', 'downBack', 'back'], buttons: ['special'], maxGapFrames: 9, bufferFrames: 8, priority: 60 },
      totalFrames: 64,
      movement: [{ range: { from: 7, to: 14 }, velocityX: 2.5 }],
      hitboxes: [{
        range: { from: 15, to: 18 },
        boxes: [{ id: 'guto-super-throw', x: 2, y: -69, width: 36, height: 66, kind: 'throw', level: 'mid', damage: 280, chipDamage: 0, hitStun: 52, blockStun: 0, hitStop: 24, priority: 10, knockbackX: 3.2, knockbackY: -13, knockdown: true, freezeFrames: 40 }],
      }],
      meterCost: 100,
      meterGainOnHit: 0,
      meterGainOnBlock: 0,
      isSuper: true,
      cinematic: 'freeze',
      lockFacing: true,
    },
  },
};
