import type { FighterDefinition } from '../types/combat';
import { CROUCHING_HURTBOXES, STANDARD_ANIMATIONS } from './shared';

export const gutoBarba: FighterDefinition = {
  id: 'guto-barba',
  name: 'GUTO BARBA',
  archetype: 'TANK / GRAPPLER',
  available: true,
  description: 'Passos firmes, golpes devastadores e agarrões curtos.',
  abilities: ['Muralha Norte', 'Gancho do Urso', 'Abraço Glacial'],
  stats: {
    maxHealth: 1250,
    walkSpeed: 1.75,
    backwardSpeed: 1.45,
    // Velocidades/aceleração verticais na escala do mundo 640x360
    // (dobradas na migração de 320x180; o tempo de voo não muda).
    jumpSpeed: 12.8,
    // Pulo diagonal curto e pesado (arquétipo tanque).
    jumpForwardSpeed: 1.9,
    jumpBackwardSpeed: 1.7,
    gravity: 0.86,
    weight: 1.28,
    pushbox: { x: -19, y: -61, width: 38, height: 61 },
  },
  standingHurtboxes: [
    { x: -15, y: -75, width: 30, height: 23, region: 'head' },
    { x: -21, y: -53, width: 42, height: 35, region: 'body' },
    { x: -18, y: -20, width: 36, height: 20, region: 'legs' },
  ],
  crouchingHurtboxes: CROUCHING_HURTBOXES,
  visualHurtboxes: [
    { x: -30, y: -150, width: 60, height: 46, region: 'head' },
    { x: -42, y: -106, width: 84, height: 106, region: 'body' },
  ],
  animations: STANDARD_ANIMATIONS,
  visual: {
    body: 0x61488e,
    accent: 0xa8e9ff,
    shadow: 0x2a2144,
    skin: 0xad7658,
  },
  moves: {
    elbow: {
      id: 'elbow',
      label: 'Cotovelada',
      state: 'lightAttack',
      animation: 'standingLight',
      command: { buttons: ['light'], maxGapFrames: 1, bufferFrames: 5, priority: 10 },
      totalFrames: 20,
      hitboxes: [{
        range: { from: 6, to: 9 },
        boxes: [{ id: 'guto-elbow', x: 8, y: -58, width: 34, height: 22, kind: 'strike', level: 'mid', damage: 66, chipDamage: 2, hitStun: 15, blockStun: 10, hitStop: 7, priority: 2, knockbackX: 2.2, knockbackY: 0 }],
      }],
      meterCost: 0,
      meterGainOnHit: 9,
      meterGainOnBlock: 4,
    },
    heavyPunch: {
      id: 'heavyPunch',
      label: 'Soco pesado',
      state: 'heavyAttack',
      animation: 'standingHeavy',
      command: { buttons: ['heavy'], maxGapFrames: 1, bufferFrames: 6, priority: 9 },
      totalFrames: 36,
      hitboxes: [{
        range: { from: 14, to: 18 },
        boxes: [{ id: 'guto-heavy', x: 6, y: -65, width: 51, height: 28, kind: 'strike', level: 'mid', damage: 122, chipDamage: 8, hitStun: 23, blockStun: 16, hitStop: 11, priority: 4, knockbackX: 5, knockbackY: -2.4, knockdown: true }],
      }],
      meterCost: 0,
      meterGainOnHit: 15,
      meterGainOnBlock: 7,
    },
    frontKick: {
      id: 'frontKick',
      label: 'Chute frontal',
      state: 'kickAttack',
      animation: 'crouchLight',
      command: { directions: ['down'], buttons: ['light'], maxGapFrames: 2, bufferFrames: 5, priority: 14 },
      totalFrames: 29,
      hitboxes: [{
        range: { from: 10, to: 14 },
        boxes: [{ id: 'guto-front-kick', x: 10, y: -118, width: 90, height: 46, kind: 'strike', level: 'low', damage: 82, chipDamage: 4, hitStun: 17, blockStun: 12, hitStop: 8, priority: 3, knockbackX: 3.3, knockbackY: 0 }],
      }],
      hurtboxes: [{ range: { from: 0, to: 29 }, boxes: CROUCHING_HURTBOXES }],
      meterCost: 0,
      meterGainOnHit: 11,
      meterGainOnBlock: 5,
    },
    ombrada: {
      id: 'ombrada',
      label: 'Ombrada',
      state: 'lightAttack',
      animation: 'forwardLight',
      command: { directions: ['forward'], buttons: ['light'], maxGapFrames: 2, bufferFrames: 5, priority: 15 },
      totalFrames: 23,
      movement: [{ range: { from: 4, to: 10 }, velocityX: 2 }],
      hitboxes: [{
        range: { from: 9, to: 12 },
        boxes: [{ id: 'guto-shoulder', x: 8, y: -60, width: 36, height: 24, kind: 'strike', level: 'mid', damage: 72, chipDamage: 3, hitStun: 15, blockStun: 11, hitStop: 7, priority: 2, knockbackX: 2.6, knockbackY: 0 }],
      }],
      meterCost: 0,
      meterGainOnHit: 10,
      meterGainOnBlock: 4,
    },
    rasteiraUrso: {
      id: 'rasteiraUrso',
      label: 'Rasteira do Urso',
      state: 'kickAttack',
      animation: 'crouchHeavy',
      command: { directions: ['down'], buttons: ['heavy'], maxGapFrames: 2, bufferFrames: 5, priority: 16 },
      totalFrames: 36,
      hitboxes: [{
        range: { from: 14, to: 18 },
        boxes: [{ id: 'guto-sweep', x: 10, y: -82, width: 104, height: 36, kind: 'strike', level: 'low', damage: 118, chipDamage: 7, hitStun: 24, blockStun: 15, hitStop: 10, priority: 3, knockbackX: 3.4, knockbackY: -3.4, knockdown: true }],
      }],
      hurtboxes: [{ range: { from: 0, to: 36 }, boxes: CROUCHING_HURTBOXES }],
      meterCost: 0,
      meterGainOnHit: 14,
      meterGainOnBlock: 6,
    },
    jumpLightNeutral: {
      id: 'jumpLightNeutral',
      label: 'Soco aéreo',
      state: 'lightAttack',
      animation: 'airLightNeutral',
      air: true,
      jumpTrajectory: 'neutral',
      command: { buttons: ['light'], maxGapFrames: 1, bufferFrames: 5, priority: 20 },
      totalFrames: 24,
      hitboxes: [{
        range: { from: 6, to: 15 },
        boxes: [{ id: 'guto-air-light', x: 6, y: -48, width: 38, height: 30, kind: 'strike', level: 'overhead', damage: 72, chipDamage: 4, hitStun: 15, blockStun: 10, hitStop: 6, priority: 2, knockbackX: 2.2, knockbackY: 0 }],
      }],
      meterCost: 0,
      meterGainOnHit: 9,
      meterGainOnBlock: 4,
    },
    jumpHeavyNeutral: {
      id: 'jumpHeavyNeutral',
      label: 'Chute aéreo',
      state: 'heavyAttack',
      animation: 'airHeavyNeutral',
      air: true,
      jumpTrajectory: 'neutral',
      command: { buttons: ['heavy'], maxGapFrames: 1, bufferFrames: 5, priority: 21 },
      totalFrames: 28,
      hitboxes: [{
        range: { from: 8, to: 17 },
        boxes: [{ id: 'guto-air-kick', x: 8, y: -140, width: 100, height: 48, kind: 'strike', level: 'overhead', damage: 120, chipDamage: 8, hitStun: 20, blockStun: 13, hitStop: 9, priority: 3, knockbackX: 3.6, knockbackY: -2.5 }],
      }],
      meterCost: 0,
      meterGainOnHit: 14,
      meterGainOnBlock: 6,
    },
    jumpLightForward: {
      id: 'jumpLightForward',
      label: 'Soco aéreo (Frente)',
      state: 'lightAttack',
      animation: 'airLightForward',
      air: true,
      jumpTrajectory: 'forward',
      command: { buttons: ['light'], maxGapFrames: 1, bufferFrames: 5, priority: 22 },
      totalFrames: 24,
      hitboxes: [{
        range: { from: 6, to: 15 },
        boxes: [{ id: 'guto-air-light-fwd', x: 12, y: -44, width: 38, height: 30, kind: 'strike', level: 'overhead', damage: 75, chipDamage: 4, hitStun: 15, blockStun: 10, hitStop: 6, priority: 2, knockbackX: 2.8, knockbackY: 0 }],
      }],
      meterCost: 0,
      meterGainOnHit: 9,
      meterGainOnBlock: 4,
    },
    jumpHeavyForward: {
      id: 'jumpHeavyForward',
      label: 'Chute aéreo (Frente)',
      state: 'heavyAttack',
      animation: 'airHeavyForward',
      air: true,
      jumpTrajectory: 'forward',
      command: { buttons: ['heavy'], maxGapFrames: 1, bufferFrames: 5, priority: 23 },
      totalFrames: 28,
      hitboxes: [{
        range: { from: 8, to: 17 },
        boxes: [{ id: 'guto-air-kick-fwd', x: 8, y: -142, width: 104, height: 50, kind: 'strike', level: 'overhead', damage: 125, chipDamage: 8, hitStun: 20, blockStun: 13, hitStop: 9, priority: 3, knockbackX: 4.5, knockbackY: -2.5 }],
      }],
      meterCost: 0,
      meterGainOnHit: 14,
      meterGainOnBlock: 6,
    },
    jumpLightBackward: {
      id: 'jumpLightBackward',
      label: 'Soco aéreo (Trás)',
      state: 'lightAttack',
      animation: 'airLightBackward',
      air: true,
      jumpTrajectory: 'backward',
      command: { buttons: ['light'], maxGapFrames: 1, bufferFrames: 5, priority: 22 },
      totalFrames: 24,
      hitboxes: [{
        range: { from: 6, to: 15 },
        boxes: [{ id: 'guto-air-light-back', x: 2, y: -44, width: 38, height: 30, kind: 'strike', level: 'overhead', damage: 70, chipDamage: 4, hitStun: 15, blockStun: 10, hitStop: 6, priority: 2, knockbackX: 1.8, knockbackY: 0 }],
      }],
      meterCost: 0,
      meterGainOnHit: 9,
      meterGainOnBlock: 4,
    },
    jumpHeavyBackward: {
      id: 'jumpHeavyBackward',
      label: 'Chute aéreo (Trás)',
      state: 'heavyAttack',
      animation: 'airHeavyBackward',
      air: true,
      jumpTrajectory: 'backward',
      command: { buttons: ['heavy'], maxGapFrames: 1, bufferFrames: 5, priority: 23 },
      totalFrames: 28,
      hitboxes: [{
        range: { from: 8, to: 17 },
        boxes: [{ id: 'guto-air-kick-back', x: 0, y: -50, width: 48, height: 34, kind: 'strike', level: 'overhead', damage: 115, chipDamage: 8, hitStun: 20, blockStun: 13, hitStop: 9, priority: 3, knockbackX: 3.0, knockbackY: -2.5 }],
      }],
      meterCost: 0,
      meterGainOnHit: 14,
      meterGainOnBlock: 6,
    },
    descendingBlow: {
      id: 'descendingBlow',
      label: 'Chute pesado',
      state: 'kickAttack',
      animation: 'forwardHeavy',
      command: { directions: ['forward'], buttons: ['heavy'], maxGapFrames: 2, bufferFrames: 5, priority: 15 },
      totalFrames: 40,
      hitboxes: [{
        range: { from: 17, to: 21 },
        boxes: [{ id: 'guto-overhead', x: 16, y: -169, width: 93, height: 52, kind: 'strike', level: 'overhead', damage: 138, chipDamage: 9, hitStun: 25, blockStun: 17, hitStop: 12, priority: 5, knockbackX: 5.5, knockbackY: -6.4, knockdown: true }],
      }],
      meterCost: 0,
      meterGainOnHit: 16,
      meterGainOnBlock: 8,
      usesVisualHurtboxes: true,
    },
    muralhaNorte: {
      id: 'muralhaNorte',
      label: 'Muralha Norte',
      state: 'specialAttack',
      animation: 'special1',
      command: { buttons: ['special'], maxGapFrames: 2, bufferFrames: 7, priority: 30 },
      totalFrames: 52,
      movement: [{ range: { from: 7, to: 35 }, velocityX: 1.8 }],
      hitboxes: [{
        range: { from: 20, to: 31 },
        boxes: [{ id: 'guto-wall', x: 12, y: -63, width: 39, height: 55, kind: 'strike', level: 'mid', damage: 104, chipDamage: 10, hitStun: 20, blockStun: 17, hitStop: 9, priority: 5, knockbackX: 4.2, knockbackY: 0 }],
      }],
      events: [{ frame: 4, type: 'grantArmor', hits: 1 }, { frame: 36, type: 'clearArmor' }],
      meterCost: 0,
      meterGainOnHit: 15,
      meterGainOnBlock: 8,
      lockFacing: true,
    },
    ganchoUrso: {
      id: 'ganchoUrso',
      label: 'Gancho do Urso',
      state: 'specialAttack',
      animation: 'special2',
      command: { directions: ['forward'], buttons: ['special'], maxGapFrames: 2, bufferFrames: 7, priority: 50 },
      totalFrames: 54,
      movement: [{ range: { from: 2, to: 7 }, velocityX: 1.2 }],
      hitboxes: [{
        range: { from: 8, to: 10 },
        boxes: [{ id: 'guto-throw', x: 28, y: -150, width: 62, height: 66, kind: 'throw', level: 'mid', damage: 155, chipDamage: 0, hitStun: 28, blockStun: 0, hitStop: 12, priority: 7, knockbackX: 4.5, knockbackY: -10, knockdown: true }],
      }],
      grab: {
        victimAnchorX: 45,
        victimAnchorY: 0,
        victimRotation: 0,
        holdStartFrame: 14,
        releaseFrame: 35,
        throwVelocityX: 4.5,
        throwVelocityY: -10,
        whiffRecoveryFrame: 40,
        victimTimeline: [
          { frame: 8, state: 'grabbedFront', poseFrame: 0, victimAnchorX: 52, victimAnchorY: 0, victimRotation: 0 },
          { frame: 9, state: 'grabbedFront', poseFrame: 1, victimAnchorX: 50, victimAnchorY: -1, victimRotation: 0 },
          { frame: 10, state: 'grabbedFront', poseFrame: 2, victimAnchorX: 48, victimAnchorY: -2, victimRotation: 0 },
          { frame: 11, state: 'grabbedFront', poseFrame: 3, victimAnchorX: 46, victimAnchorY: -4, victimRotation: 0 },
          { frame: 12, state: 'grabbedFront', poseFrame: 4, victimAnchorX: 44, victimAnchorY: -6, victimRotation: 0 },
          { frame: 13, state: 'grabbedFront', poseFrame: 5, victimAnchorX: 43, victimAnchorY: -8, victimRotation: 0 },
          { frame: 14, state: 'grabbedLifted', poseFrame: 0, victimAnchorX: 44, victimAnchorY: -10, victimRotation: 0 },
          { frame: 16, state: 'grabbedLifted', poseFrame: 1, victimAnchorX: 45, victimAnchorY: -22, victimRotation: 0 },
          { frame: 18, state: 'grabbedLifted', poseFrame: 2, victimAnchorX: 47, victimAnchorY: -36, victimRotation: 0 },
          { frame: 20, state: 'grabbedLifted', poseFrame: 3, victimAnchorX: 49, victimAnchorY: -50, victimRotation: 0 },
          { frame: 22, state: 'grabbedLifted', poseFrame: 4, victimAnchorX: 50, victimAnchorY: -64, victimRotation: 0 },
          { frame: 24, state: 'grabbedLifted', poseFrame: 5, victimAnchorX: 50, victimAnchorY: -74, victimRotation: 0 },
          { frame: 26, state: 'grabbedLifted', poseFrame: 6, victimAnchorX: 51, victimAnchorY: -80, victimRotation: 0 },
          { frame: 29, state: 'grabbedLifted', poseFrame: 7, victimAnchorX: 52, victimAnchorY: -82, victimRotation: 0 },
          { frame: 32, state: 'grabbedLifted', poseFrame: 7, victimAnchorX: 58, victimAnchorY: -85, victimRotation: 0 },
          { frame: 34, state: 'grabbedLifted', poseFrame: 7, victimAnchorX: 70, victimAnchorY: -80, victimRotation: 0 },
        ],
        victimOffsets: {
          'rafa-mare': { anchorOffsetX: 0, anchorOffsetY: 0 },
          'astro-riso': { anchorOffsetX: -2, anchorOffsetY: 2 },
          'guto-barba': { anchorOffsetX: 8, anchorOffsetY: 0 },
        },
      },
      meterCost: 0,
      meterGainOnHit: 18,
      meterGainOnBlock: 0,
      lockFacing: true,
      usesVisualHurtboxes: true,
    },
    abracoGlacial: {
      id: 'abracoGlacial',
      label: 'Abraço Glacial',
      state: 'specialAttack',
      animation: 'special3',
      command: { directions: ['down'], buttons: ['special'], maxGapFrames: 2, bufferFrames: 7, priority: 60 },
      totalFrames: 110,
      movement: [{ range: { from: 3, to: 8 }, velocityX: 2.5 }],
      hitboxes: [{
        range: { from: 9, to: 12 },
        boxes: [{ id: 'guto-super-throw', x: 30, y: -156, width: 72, height: 74, kind: 'throw', level: 'mid', damage: 280, chipDamage: 0, hitStun: 52, blockStun: 0, hitStop: 24, priority: 10, knockbackX: 3.2, knockbackY: -13, knockdown: true }],
      }],
      grab: {
        victimAnchorX: 42,
        victimAnchorY: -4,
        victimRotation: 0,
        holdStartFrame: 19,
        releaseFrame: 91,
        throwVelocityX: 3.2,
        throwVelocityY: -13,
        whiffRecoveryFrame: 99,
        victimTimeline: [
          { frame: 9, state: 'grabbedFront', poseFrame: 0, victimAnchorX: 50, victimAnchorY: 0, victimRotation: 0 },
          { frame: 10, state: 'grabbedFront', poseFrame: 1, victimAnchorX: 48, victimAnchorY: -1, victimRotation: 0 },
          { frame: 12, state: 'grabbedFront', poseFrame: 2, victimAnchorX: 46, victimAnchorY: -2, victimRotation: 0 },
          { frame: 14, state: 'grabbedFront', poseFrame: 3, victimAnchorX: 44, victimAnchorY: -3, victimRotation: 0 },
          { frame: 16, state: 'grabbedFront', poseFrame: 4, victimAnchorX: 43, victimAnchorY: -4, victimRotation: 0 },
          { frame: 18, state: 'grabbedFront', poseFrame: 5, victimAnchorX: 42, victimAnchorY: -4, victimRotation: 0 },
          { frame: 21, state: 'grabbedFront', poseFrame: 6, victimAnchorX: 41, victimAnchorY: -4, victimRotation: 0 },
          { frame: 27, state: 'grabbedFront', poseFrame: 7, victimAnchorX: 41, victimAnchorY: -4, victimRotation: 0 },
          { frame: 28, state: 'frozen', poseFrame: 0, victimAnchorX: 41, victimAnchorY: -4, victimRotation: 0 },
          { frame: 90, state: 'frozen', poseFrame: 0, victimAnchorX: 41, victimAnchorY: -4, victimRotation: 0 },
        ],
        victimOffsets: {
          'rafa-mare': { anchorOffsetX: 0, anchorOffsetY: 0 },
          'astro-riso': { anchorOffsetX: -2, anchorOffsetY: 0 },
          'guto-barba': { anchorOffsetX: 8, anchorOffsetY: 0 },
        },
      },
      meterCost: 100,
      meterGainOnHit: 0,
      meterGainOnBlock: 0,
      isSuper: true,
      cinematic: 'freeze',
      lockFacing: true,
      usesVisualHurtboxes: true,
    },
  },
};
