import type { FighterDefinition } from '../types/combat';
import { CROUCHING_HURTBOXES, STANDARD_ANIMATIONS, STANDING_HURTBOXES } from './shared';

export const rafaMare: FighterDefinition = {
  id: 'rafa-mare',
  name: 'RAFA MARÉ',
  archetype: 'AGILE / RUSHDOWN',
  available: true,
  description: 'Pressão curta, avanço rápido e ritmo crescente.',
  abilities: ['Mão da Maré', 'Chute da Ressaca', 'Eco Tatuado'],
  stats: {
    maxHealth: 1000,
    walkSpeed: 3.05,
    backwardSpeed: 2.5,
    // Velocidades/aceleração verticais na escala do mundo 640x360
    // (dobradas na migração de 320x180; o tempo de voo não muda).
    jumpSpeed: 15.6,
    // Pulo diagonal mais rápido e longo (arquétipo ágil).
    jumpForwardSpeed: 3.3,
    jumpBackwardSpeed: 2.9,
    gravity: 0.92,
    weight: 0.9,
    pushbox: { x: -14, y: -54, width: 28, height: 54 },
  },
  standingHurtboxes: STANDING_HURTBOXES,
  crouchingHurtboxes: CROUCHING_HURTBOXES,
  animations: STANDARD_ANIMATIONS,
  passive: {
    id: 'eco-tatuado',
    label: 'ECO TATUADO',
    damageThreshold: 240,
    durationFrames: 300,
    speedMultiplier: 1.22,
  },
  visual: {
    body: 0x127da8,
    accent: 0x29d9ff,
    shadow: 0x08344d,
    skin: 0xc98b6f,
  },
  projectiles: {
    ondaCurta: {
      id: 'onda-curta',
      offsetX: 28,
      offsetY: -52,
      velocityX: 4.1,
      lifeFrames: 52,
      hitbox: {
        id: 'onda-curta',
        x: -15,
        y: -10,
        width: 30,
        height: 20,
        kind: 'projectile',
        level: 'mid',
        damage: 112,
        chipDamage: 8,
        hitStun: 20,
        blockStun: 15,
        hitStop: 8,
        priority: 4,
        knockbackX: 4,
        knockbackY: -2,
      },
    },
  },
  moves: {
    lightPunch: {
      id: 'lightPunch',
      label: 'Soco rápido',
      state: 'lightAttack',
      animation: 'attack',
      command: { buttons: ['light'], maxGapFrames: 1, bufferFrames: 5, priority: 10 },
      totalFrames: 15,
      hitboxes: [{
        range: { from: 4, to: 6 },
        boxes: [{ id: 'rafa-jab', x: 10, y: -54, width: 29, height: 15, kind: 'strike', level: 'high', damage: 45, chipDamage: 0, hitStun: 11, blockStun: 8, hitStop: 5, priority: 1, knockbackX: 1.6, knockbackY: 0 }],
      }],
      cancels: [{ range: { from: 7, to: 10 }, into: ['maoDaMare'], condition: 'hit' }],
      meterCost: 0,
      meterGainOnHit: 8,
      meterGainOnBlock: 3,
    },
    heavyPunch: {
      id: 'heavyPunch',
      label: 'Soco forte',
      state: 'heavyAttack',
      animation: 'attack',
      command: { buttons: ['heavy'], maxGapFrames: 1, bufferFrames: 6, priority: 9 },
      totalFrames: 29,
      hitboxes: [{
        range: { from: 10, to: 13 },
        boxes: [{ id: 'rafa-heavy', x: 7, y: -58, width: 40, height: 22, kind: 'strike', level: 'mid', damage: 88, chipDamage: 5, hitStun: 18, blockStun: 13, hitStop: 8, priority: 2, knockbackX: 3.3, knockbackY: -1 }],
      }],
      meterCost: 0,
      meterGainOnHit: 12,
      meterGainOnBlock: 5,
    },
    lowKick: {
      id: 'lowKick',
      label: 'Chute baixo',
      state: 'kickAttack',
      animation: 'attack',
      command: { directions: ['down'], buttons: ['light'], maxGapFrames: 2, bufferFrames: 5, priority: 14 },
      totalFrames: 23,
      hitboxes: [{
        range: { from: 7, to: 10 },
        boxes: [{ id: 'rafa-low', x: 8, y: -21, width: 42, height: 15, kind: 'strike', level: 'low', damage: 58, chipDamage: 2, hitStun: 14, blockStun: 10, hitStop: 6, priority: 1, knockbackX: 2.1, knockbackY: 0 }],
      }],
      hurtboxes: [{ range: { from: 0, to: 23 }, boxes: CROUCHING_HURTBOXES }],
      meterCost: 0,
      meterGainOnHit: 9,
      meterGainOnBlock: 4,
    },
    avancoMare: {
      id: 'avancoMare',
      label: 'Palma avançando',
      state: 'lightAttack',
      animation: 'attack',
      command: { directions: ['forward'], buttons: ['light'], maxGapFrames: 2, bufferFrames: 5, priority: 15 },
      totalFrames: 19,
      movement: [{ range: { from: 3, to: 8 }, velocityX: 2.7 }],
      hitboxes: [{
        range: { from: 8, to: 11 },
        boxes: [{ id: 'rafa-advance', x: 10, y: -56, width: 32, height: 16, kind: 'strike', level: 'high', damage: 55, chipDamage: 2, hitStun: 12, blockStun: 9, hitStop: 5, priority: 1, knockbackX: 2, knockbackY: 0 }],
      }],
      meterCost: 0,
      meterGainOnHit: 9,
      meterGainOnBlock: 4,
    },
    rasteira: {
      id: 'rasteira',
      label: 'Rasteira',
      state: 'kickAttack',
      animation: 'attack',
      command: { directions: ['down'], buttons: ['heavy'], maxGapFrames: 2, bufferFrames: 5, priority: 16 },
      totalFrames: 31,
      hitboxes: [{
        range: { from: 11, to: 15 },
        boxes: [{ id: 'rafa-sweep', x: 6, y: -16, width: 46, height: 16, kind: 'strike', level: 'low', damage: 92, chipDamage: 5, hitStun: 22, blockStun: 14, hitStop: 8, priority: 2, knockbackX: 3, knockbackY: -3, knockdown: true }],
      }],
      hurtboxes: [{ range: { from: 0, to: 31 }, boxes: CROUCHING_HURTBOXES }],
      meterCost: 0,
      meterGainOnHit: 12,
      meterGainOnBlock: 5,
    },
    jumpLight: {
      id: 'jumpLight',
      label: 'Soco aéreo',
      state: 'lightAttack',
      animation: 'attack',
      air: true,
      command: { buttons: ['light'], maxGapFrames: 1, bufferFrames: 5, priority: 20 },
      totalFrames: 22,
      hitboxes: [{
        range: { from: 5, to: 14 },
        boxes: [{ id: 'rafa-air-light', x: 6, y: -44, width: 34, height: 28, kind: 'strike', level: 'overhead', damage: 58, chipDamage: 3, hitStun: 13, blockStun: 9, hitStop: 5, priority: 2, knockbackX: 1.8, knockbackY: 0 }],
      }],
      meterCost: 0,
      meterGainOnHit: 8,
      meterGainOnBlock: 3,
    },
    jumpKick: {
      id: 'jumpKick',
      label: 'Chute aéreo',
      state: 'heavyAttack',
      animation: 'attack',
      air: true,
      command: { buttons: ['heavy'], maxGapFrames: 1, bufferFrames: 5, priority: 21 },
      totalFrames: 26,
      hitboxes: [{
        range: { from: 7, to: 16 },
        boxes: [{ id: 'rafa-air-kick', x: 4, y: -50, width: 44, height: 32, kind: 'strike', level: 'overhead', damage: 96, chipDamage: 6, hitStun: 18, blockStun: 12, hitStop: 8, priority: 3, knockbackX: 3.2, knockbackY: -2 }],
      }],
      meterCost: 0,
      meterGainOnHit: 12,
      meterGainOnBlock: 5,
    },
    highKick: {
      id: 'highKick',
      label: 'Chute alto',
      state: 'kickAttack',
      animation: 'attack',
      command: { directions: ['forward'], buttons: ['heavy'], maxGapFrames: 2, bufferFrames: 5, priority: 15 },
      totalFrames: 32,
      hitboxes: [{
        range: { from: 12, to: 16 },
        boxes: [{ id: 'rafa-high', x: 5, y: -76, width: 48, height: 24, kind: 'strike', level: 'overhead', damage: 102, chipDamage: 6, hitStun: 20, blockStun: 14, hitStop: 9, priority: 3, knockbackX: 3.8, knockbackY: -3.6 }],
      }],
      meterCost: 0,
      meterGainOnHit: 14,
      meterGainOnBlock: 6,
    },
    maoDaMare: {
      id: 'maoDaMare',
      label: 'Mão da Maré',
      state: 'specialAttack',
      animation: 'attack',
      command: { directions: ['down', 'downForward', 'forward'], buttons: ['special'], maxGapFrames: 8, bufferFrames: 8, priority: 35 },
      totalFrames: 39,
      hitboxes: [],
      events: [{ frame: 13, type: 'spawnProjectile', projectileId: 'onda-curta' }],
      meterCost: 0,
      meterGainOnHit: 16,
      meterGainOnBlock: 7,
      lockFacing: true,
    },
    ecoTatuado: {
      id: 'ecoTatuado',
      label: 'Eco Tatuado',
      state: 'specialAttack',
      animation: 'attack',
      command: { directions: ['down', 'downBack', 'back'], buttons: ['special'], maxGapFrames: 8, bufferFrames: 8, priority: 36 },
      totalFrames: 36,
      hitboxes: [],
      events: [{ frame: 12, type: 'grantBuff', durationFrames: 300 }],
      meterCost: 50,
      meterGainOnHit: 0,
      meterGainOnBlock: 0,
      lockFacing: true,
    },
    chuteRessaca: {
      id: 'chuteRessaca',
      label: 'Chute da Ressaca',
      state: 'specialAttack',
      animation: 'attack',
      command: { directions: ['down', 'downForward', 'forward'], buttons: ['heavy'], maxGapFrames: 8, bufferFrames: 8, priority: 60 },
      totalFrames: 56,
      movement: [{ range: { from: 8, to: 20 }, velocityX: 7.4 }],
      hitboxes: [{
        range: { from: 17, to: 22 },
        boxes: [{ id: 'rafa-super', x: 4, y: -64, width: 58, height: 40, kind: 'strike', level: 'mid', damage: 230, chipDamage: 18, hitStun: 31, blockStun: 20, hitStop: 14, priority: 8, knockbackX: 7.2, knockbackY: -9, knockdown: true }],
      }],
      meterCost: 100,
      meterGainOnHit: 0,
      meterGainOnBlock: 0,
      isSuper: true,
      cinematic: 'rush',
      lockFacing: true,
    },
  },
};
