import type {
  FighterAnimationAsset,
  FighterEffectAsset,
  FighterSpriteAsset,
  SharedFighterAnimationId,
} from '../../types/assets';
import { FIGHTER_OPAQUE_BOTTOM_PADDING } from './groundContact';

const files: Readonly<Record<SharedFighterAnimationId, string>> = {
  idle: 'idle.png',
  walk: 'corrida.png',
  walkBackward: 'walk-backward.png',
  jumpNeutral: 'jump-neutral.png',
  jumpForward: 'jump-forward.png',
  jumpBackward: 'jump-backward.png',
  fall: 'fall.png',
  landing: 'landing.png',
  crouch: 'crouch.png',
  standingLight: 'standing-light.png',
  standingHeavy: 'standing-heavy.png',
  forwardLight: 'forward-light.png',
  forwardHeavy: 'forward-heavy.png',
  crouchLight: 'crouch-light.png',
  crouchHeavy: 'crouch-heavy.png',
  airLightNeutral: 'air-light-neutral.png',
  airHeavyNeutral: 'air-heavy-neutral.png',
  airLightForward: 'air-light-forward.png',
  airHeavyForward: 'air-heavy-forward.png',
  airLightBackward: 'air-light-backward.png',
  airHeavyBackward: 'air-heavy-backward.png',
  special1: 'sorriso-relampago.png',
  special2: 'rajada-neon.png',
  special3: 'astro-giro.png',
  blockStanding: 'block-standing.png',
  blockCrouching: 'block-crouching.png',
  hit: 'hit.png',
  knockdown: 'knockdown.png',
  wakeUp: 'wake-up.png',
  grabbedFront: 'grabbed-front.png',
  grabbedLifted: 'grabbed-lifted.png',
  thrown: 'thrown.png',
  frozen: 'frozen.png',
  knockout: 'knockout.png',
  victory: 'victory.png',
};

const FRAME_SIZE = 256;

function animation(
  id: SharedFighterAnimationId,
  frameRate: number,
  repeat: number,
  frames = 4,
): FighterAnimationAsset {
  return {
    id,
    key: `astro-riso-${id}`,
    path: `assets/fighters/astro-riso/${files[id]}`,
    frameWidth: FRAME_SIZE,
    frameHeight: FRAME_SIZE,
    frames,
    layout: 'horizontal',
    frameRate,
    repeat,
  };
}

function effect(
  id: string,
  file: string,
  moveId: string,
  activeRange: FighterEffectAsset['activeRange'],
  offset: FighterEffectAsset['offset'],
): FighterEffectAsset {
  return {
    id,
    key: `astro-riso-effect-${id}`,
    path: `assets/fighters/astro-riso/${file}`,
    moveId,
    usage: 'attached',
    ...(activeRange ? { activeRange } : {}),
    origin: { x: 0.5, y: 0.5 },
    offset,
    scale: 1,
    frameWidth: FRAME_SIZE,
    frameHeight: FRAME_SIZE,
    frames: 4,
    layout: 'horizontal',
    frameRate: 12,
    repeat: 0,
  };
}

// Todos os frames corporais são normalizados com 6 px sob a última sola.
export const astroRisoSpriteAsset: FighterSpriteAsset = {
  fighterId: 'astro-riso',
  frameWidth: FRAME_SIZE,
  frameHeight: FRAME_SIZE,
  origin: { x: 0.5, y: 1 },
  scale: 1,
  visualOffset: { x: 0, y: FIGHTER_OPAQUE_BOTTOM_PADDING['astro-riso'] },
  legacyHitboxGuide: [{ x: 12, y: -114, width: 86, height: 58 }],
  legacyHurtboxGuide: [
    { x: -21, y: -134, width: 42, height: 42 },
    { x: -28, y: -92, width: 56, height: 92 },
  ],
  effects: [
    effect('sorriso-relampago', 'sorriso-relampago-effect.png', 'sorrisoRelampago', { from: 5, to: 20 }, { x: 34, y: -84 }),
    effect('rajada-neon', 'rajada-neon-effect.png', 'rajadaNeon', { from: 8, to: 31 }, { x: 36, y: -82 }),
    effect('astro-giro', 'astro-giro-effect.png', 'astroGiro', { from: 12, to: 39 }, { x: 4, y: -83 }),
  ],
  movePhases: {},
  animations: {
    idle: animation('idle', 8, -1),
    walk: animation('walk', 13, -1),
    walkBackward: animation('walkBackward', 10, -1),
    jumpNeutral: animation('jumpNeutral', 10, 0),
    jumpForward: animation('jumpForward', 10, 0),
    jumpBackward: animation('jumpBackward', 10, 0),
    fall: animation('fall', 10, 0),
    landing: animation('landing', 14, 0),
    crouch: animation('crouch', 8, 0),
    standingLight: animation('standingLight', 15, 0),
    standingHeavy: animation('standingHeavy', 11, 0),
    forwardLight: animation('forwardLight', 15, 0),
    forwardHeavy: animation('forwardHeavy', 11, 0),
    crouchLight: animation('crouchLight', 15, 0),
    crouchHeavy: animation('crouchHeavy', 11, 0),
    airLightNeutral: animation('airLightNeutral', 15, 0),
    airHeavyNeutral: animation('airHeavyNeutral', 11, 0),
    airLightForward: animation('airLightForward', 15, 0),
    airHeavyForward: animation('airHeavyForward', 11, 0),
    airLightBackward: animation('airLightBackward', 15, 0),
    airHeavyBackward: animation('airHeavyBackward', 11, 0),
    special1: animation('special1', 12, 0),
    special2: animation('special2', 14, 0),
    special3: animation('special3', 12, 0),
    blockStanding: animation('blockStanding', 9, 0),
    blockCrouching: animation('blockCrouching', 9, 0),
    hit: animation('hit', 12, 0),
    knockdown: animation('knockdown', 8, 0),
    wakeUp: animation('wakeUp', 11, 0),
    grabbedFront: animation('grabbedFront', 30, 0, 8),
    grabbedLifted: animation('grabbedLifted', 30, 0, 8),
    thrown: animation('thrown', 11, 0),
    frozen: animation('frozen', 8, -1),
    knockout: animation('knockout', 7, 0),
    victory: animation('victory', 9, -1),
  },
};
