import type {
  FighterAnimationAsset,
  FighterAnimationId,
  FighterEffectAsset,
  FighterSpriteAsset,
} from '../../types/assets';
import { FIGHTER_OPAQUE_BOTTOM_PADDING } from './groundContact';

const files: Readonly<Record<FighterAnimationId, string>> = {
  idle: 'idle.png',
  walk: 'corrida.png',
  walkBackward: 'walk-backward.png',
  jumpNeutral: 'jump-neutral.png',
  jumpForward: 'jump-forward.png',
  jumpBackward: 'jump-backward.png',
  fall: 'fall.png',
  landing: 'landing.png',
  crouch: 'crouch.png',
  standingLight: 'standing-light.png',
  standingHeavy: 'standing-heavy.png',
  forwardLight: 'forward-light.png',
  forwardHeavy: 'forward-heavy.png',
  crouchLight: 'crouch-light.png',
  crouchHeavy: 'crouch-heavy.png',
  airLightNeutral: 'air-light-neutral.png',
  airHeavyNeutral: 'air-heavy-neutral.png',
  airLightForward: 'air-light-forward.png',
  airHeavyForward: 'air-heavy-forward.png',
  airLightBackward: 'air-light-backward.png',
  airHeavyBackward: 'air-heavy-backward.png',
  special1: 'muralha-norte.png',
  special2: 'gancho-do-urso-startup.png',
  special2Grab: 'gancho-do-urso-grab.png',
  special2Hold: 'gancho-do-urso-hold.png',
  special2Throw: 'gancho-do-urso-throw.png',
  special2Recovery: 'gancho-do-urso-recovery.png',
  special3: 'abraco-glacial-startup.png',
  special3Grab: 'abraco-glacial-grab.png',
  special3Hold: 'abraco-glacial-hold.png',
  special3Freeze: 'abraco-glacial-freeze.png',
  special3Finish: 'abraco-glacial-finish.png',
  blockStanding: 'block-standing.png',
  blockCrouching: 'block-crouching.png',
  hit: 'hit.png',
  knockdown: 'knockdown.png',
  wakeUp: 'wake-up.png',
  grabbedFront: 'grabbed-front.png',
  grabbedLifted: 'grabbed-lifted.png',
  thrown: 'thrown.png',
  frozen: 'frozen.png',
  knockout: 'knockout.png',
  victory: 'victory.png',
};

const FRAME_SIZE = 288;

function animation(id: FighterAnimationId, frameRate: number, repeat: number): FighterAnimationAsset {
  return {
    id,
    key: `guto-barba-${id}`,
    path: `assets/fighters/guto-barba/${files[id]}`,
    frameWidth: FRAME_SIZE,
    frameHeight: FRAME_SIZE,
    frames: 4,
    layout: 'horizontal',
    frameRate,
    repeat,
  };
}

function effect(
  id: string,
  file: string,
  moveId: string,
  activeRange: FighterEffectAsset['activeRange'],
  offset: FighterEffectAsset['offset'],
  attachTo?: 'attacker' | 'victim',
): FighterEffectAsset {
  return {
    id,
    key: `guto-barba-effect-${id}`,
    path: `assets/fighters/guto-barba/${file}`,
    moveId,
    usage: 'attached',
    attachTo: attachTo ?? 'attacker',
    ...(activeRange ? { activeRange } : {}),
    origin: { x: 0.5, y: 0.5 },
    offset,
    scale: 1,
    frameWidth: FRAME_SIZE,
    frameHeight: FRAME_SIZE,
    frames: 4,
    layout: 'horizontal',
    frameRate: 10,
    repeat: 0,
  };
}

// Todos os frames corporais foram medidos: há 6 px transparentes abaixo da sola.
export const gutoBarbaSpriteAsset: FighterSpriteAsset = {
  fighterId: 'guto-barba',
  frameWidth: FRAME_SIZE,
  frameHeight: FRAME_SIZE,
  origin: { x: 0.5, y: 1 },
  scale: 1,
  visualOffset: { x: 0, y: FIGHTER_OPAQUE_BOTTOM_PADDING['guto-barba'] },
  hitboxGuide: [{ x: 8, y: -132, width: 108, height: 84 }],
  hurtboxGuide: [
    { x: -30, y: -150, width: 60, height: 46 },
    { x: -42, y: -106, width: 84, height: 106 },
  ],
  effects: [
    effect('muralha-norte', 'muralha-norte-effect.png', 'muralhaNorte', { from: 4, to: 36 }, { x: 36, y: -112 }),
    effect('abraco-glacial', 'abraco-glacial-effect.png', 'abracoGlacial', { from: 35, to: 79 }, { x: 0, y: -116 }, 'victim'),
  ],
  movePhases: {
    ganchoUrso: [
      { animation: 'special2', range: { from: 0, to: 8 } },
      { animation: 'special2Grab', range: { from: 9, to: 12 } },
      { animation: 'special2Hold', range: { from: 13, to: 26 } },
      { animation: 'special2Throw', range: { from: 27, to: 32 } },
      { animation: 'special2Recovery', range: { from: 33, to: 42 } },
    ],
    abracoGlacial: [
      { animation: 'special3', range: { from: 0, to: 14 } },
      { animation: 'special3Grab', range: { from: 15, to: 19 } },
      { animation: 'special3Hold', range: { from: 20, to: 34 } },
      { animation: 'special3Freeze', range: { from: 35, to: 79 } },
      { animation: 'special3Finish', range: { from: 80, to: 93 } },
    ],
  },
  animations: {
    idle: animation('idle', 5, -1),
    walk: animation('walk', 7, -1),
    walkBackward: animation('walkBackward', 6, -1),
    jumpNeutral: animation('jumpNeutral', 6, 0),
    jumpForward: animation('jumpForward', 6, 0),
    jumpBackward: animation('jumpBackward', 6, 0),
    fall: animation('fall', 6, 0),
    landing: animation('landing', 8, 0),
    crouch: animation('crouch', 5, 0),
    standingLight: animation('standingLight', 9, 0),
    standingHeavy: animation('standingHeavy', 7, 0),
    forwardLight: animation('forwardLight', 9, 0),
    forwardHeavy: animation('forwardHeavy', 7, 0),
    crouchLight: animation('crouchLight', 9, 0),
    crouchHeavy: animation('crouchHeavy', 7, 0),
    airLightNeutral: animation('airLightNeutral', 9, 0),
    airHeavyNeutral: animation('airHeavyNeutral', 7, 0),
    airLightForward: animation('airLightForward', 9, 0),
    airHeavyForward: animation('airHeavyForward', 7, 0),
    airLightBackward: animation('airLightBackward', 10, 0),
    airHeavyBackward: animation('airHeavyBackward', 7, 0),
    special1: animation('special1', 10, 0),
    special2: animation('special2', 30, 0),
    special2Grab: animation('special2Grab', 60, 0),
    special2Hold: animation('special2Hold', 18, -1),
    special2Throw: animation('special2Throw', 40, 0),
    special2Recovery: animation('special2Recovery', 24, 0),
    special3: animation('special3', 18, 0),
    special3Grab: animation('special3Grab', 48, 0),
    special3Hold: animation('special3Hold', 16, -1),
    special3Freeze: animation('special3Freeze', 16, -1),
    special3Finish: animation('special3Finish', 18, 0),
    blockStanding: animation('blockStanding', 7, 0),
    blockCrouching: animation('blockCrouching', 7, 0),
    hit: animation('hit', 10, 0),
    knockdown: animation('knockdown', 6, 0),
    wakeUp: animation('wakeUp', 7, 0),
    grabbedFront: animation('grabbedFront', 8, -1),
    grabbedLifted: animation('grabbedLifted', 8, -1),
    thrown: animation('thrown', 8, 0),
    frozen: animation('frozen', 7, -1),
    knockout: animation('knockout', 5, 0),
    victory: animation('victory', 6, -1),
  },
};
