import type {
  FighterAnimationAsset,
  FighterEffectAsset,
  FighterSpriteAsset,
  SharedFighterAnimationId,
} from '../../types/assets';
import { FIGHTER_OPAQUE_BOTTOM_PADDING } from './groundContact';

const files: Readonly<Record<SharedFighterAnimationId, string>> = {
  idle: 'idle.png',
  walk: 'corrida.png',
  walkBackward: 'walk-backward.png',
  jumpNeutral: 'jump-neutral.png',
  jumpForward: 'jump-forward.png',
  jumpBackward: 'jump-backward.png',
  fall: 'fall.png',
  landing: 'landing.png',
  crouch: 'crouch.png',
  standingLight: 'standing-light.png',
  standingHeavy: 'standing-heavy.png',
  forwardLight: 'forward-light.png',
  forwardHeavy: 'forward-heavy.png',
  crouchLight: 'crouch-light.png',
  crouchHeavy: 'crouch-heavy.png',
  airLightNeutral: 'air-light-neutral.png',
  airHeavyNeutral: 'air-heavy-neutral.png',
  airLightForward: 'air-light-forward.png',
  airHeavyForward: 'air-heavy-forward.png',
  airLightBackward: 'air-light-backward.png',
  airHeavyBackward: 'air-heavy-backward.png',
  special1: 'olhar-frio.png',
  special2: 'impacto-sombrio.png',
  special3: 'pressao-violeta.png',
  blockStanding: 'block-standing.png',
  blockCrouching: 'block-crouching.png',
  hit: 'hit.png',
  knockdown: 'knockdown.png',
  wakeUp: 'wake-up.png',
  grabbedFront: 'grabbed-front.png',
  grabbedLifted: 'grabbed-lifted.png',
  thrown: 'thrown.png',
  frozen: 'frozen.png',
  knockout: 'knockout.png',
  victory: 'victory.png',
};

const FRAME_SIZE = 256;

function animation(
  id: SharedFighterAnimationId,
  frameRate: number,
  repeat: number,
  frames = 4,
): FighterAnimationAsset {
  return {
    id,
    key: `leo-violeta-${id}`,
    path: `assets/fighters/leo-violeta/${files[id]}`,
    frameWidth: FRAME_SIZE,
    frameHeight: FRAME_SIZE,
    frames,
    layout: 'horizontal',
    frameRate,
    repeat,
  };
}

function effect(
  id: string,
  file: string,
  moveId: string,
  activeRange: FighterEffectAsset['activeRange'],
  offset: FighterEffectAsset['offset'],
  usage: FighterEffectAsset['usage'] = 'attached',
): FighterEffectAsset {
  return {
    id,
    key: `leo-violeta-effect-${id}`,
    path: `assets/fighters/leo-violeta/${file}`,
    moveId,
    usage,
    ...(activeRange ? { activeRange } : {}),
    origin: { x: 0.5, y: 0.5 },
    offset,
    scale: 1,
    frameWidth: FRAME_SIZE,
    frameHeight: FRAME_SIZE,
    frames: 4,
    layout: 'horizontal',
    frameRate: 12,
    repeat: 0,
  };
}

export const leoVioletaSpriteAsset: FighterSpriteAsset = {
  fighterId: 'leo-violeta',
  frameWidth: FRAME_SIZE,
  frameHeight: FRAME_SIZE,
  origin: { x: 0.5, y: 1 },
  scale: 1,
  visualOffset: { x: 0, y: FIGHTER_OPAQUE_BOTTOM_PADDING['leo-violeta'] },
  legacyHitboxGuide: [{ x: 12, y: -118, width: 88, height: 62 }],
  legacyHurtboxGuide: [
    { x: -20, y: -132, width: 40, height: 40 },
    { x: -30, y: -92, width: 60, height: 92 },
  ],
  effects: [
    effect('olhar-frio', 'olhar-frio-effect.png', 'olharFrio', undefined, { x: 0, y: 0 }, 'projectile'),
    effect('impacto-sombrio', 'impacto-sombrio-effect.png', 'impactoSombrio', { from: 8, to: 20 }, { x: 30, y: -82 }),
    effect('pressao-violeta', 'pressao-violeta-effect.png', 'pressaoVioleta', { from: 10, to: 46 }, { x: 7, y: -84 }),
  ],
  movePhases: {},
  animations: {
    idle: animation('idle', 8, -1),
    walk: animation('walk', 12, -1),
    walkBackward: animation('walkBackward', 10, -1),
    jumpNeutral: animation('jumpNeutral', 10, 0),
    jumpForward: animation('jumpForward', 10, 0),
    jumpBackward: animation('jumpBackward', 10, 0),
    fall: animation('fall', 10, 0),
    landing: animation('landing', 14, 0),
    crouch: animation('crouch', 8, 0),
    standingLight: animation('standingLight', 14, 0),
    standingHeavy: animation('standingHeavy', 10, 0),
    forwardLight: animation('forwardLight', 13, 0),
    forwardHeavy: animation('forwardHeavy', 10, 0),
    crouchLight: animation('crouchLight', 14, 0),
    crouchHeavy: animation('crouchHeavy', 10, 0),
    airLightNeutral: animation('airLightNeutral', 14, 0),
    airHeavyNeutral: animation('airHeavyNeutral', 10, 0),
    airLightForward: animation('airLightForward', 14, 0),
    airHeavyForward: animation('airHeavyForward', 10, 0),
    airLightBackward: animation('airLightBackward', 14, 0),
    airHeavyBackward: animation('airHeavyBackward', 10, 0),
    special1: animation('special1', 12, 0),
    special2: animation('special2', 12, 0),
    special3: animation('special3', 12, 0),
    blockStanding: animation('blockStanding', 9, 0),
    blockCrouching: animation('blockCrouching', 9, 0),
    hit: animation('hit', 12, 0),
    knockdown: animation('knockdown', 8, 0),
    wakeUp: animation('wakeUp', 11, 0),
    grabbedFront: animation('grabbedFront', 30, 0, 8),
    grabbedLifted: animation('grabbedLifted', 30, 0, 8),
    thrown: animation('thrown', 11, 0),
    frozen: animation('frozen', 8, -1),
    knockout: animation('knockout', 7, 0),
    victory: animation('victory', 9, -1),
  },
};
